enum statusOficio {
    ENCARTEIRADO = 'ENCARTEIRADO',
    NEGOCIACAO = 'NEGOCIAÇÃO',
    ANALISE_JURIDICA = 'ANÁLISE JURÍDICA',
    ANALISE_DE_CESSIONARIO = 'ANÁLISE DE CESSIONÁRIO',
    CESSAO = 'CESSÃO',
    REGISTRO_DE_CESSAO = 'REGISTRO DE CESSÃO',
    CERTIDAO_CFJ = 'CERTIDÃO CFJ',
    EMISSAO_CVLD = 'EMISSÃO CVLD',
    RE_CESSAO = 'RE-CESSÃO',
    ASSOCIACAO_PGFN = 'ASSOCIAÇÃO PGFN',
    EXPEDICAO_ALVARA = 'EXPEDIÇÃO ALVARÁ',
    AGUARDANDO_PAGAMENTO = 'AGUARDANDO PAGAMENTO',
    CONCLUIDO = 'CONCLUÍDO',
}

export default statusOficio;