const regimeEnteDevedor = {
    MA: {
        COMUM: [
            'AÇAILÂNDIA',
            'AFONSO CUNHA',
            'AGUA DOCE DO MARANHÃO',
            'ALCÂNTARA',
            'ALTO ALEGRE DO PINDARÉ',
            'ANAPURUS',
            'ARAGUANÃ',
            'ARARI',
            'BACABAL',
            'BACURITUBA',
            'BALSAS',
            'BARRA DO CORDA',
            'BELA VISTA DO MARANHÃO',
            'BERNARDO DO MEARIM',
            'BOM JARDIM',
            'BOM JESUS DAS SELVAS',
            'BOM LUGAR',
            'BREJO',
            'CAJARI',
            'CAMPESTRE DO MARANHÃO',
            'CÂNDIDO MENDES',
            'CAPINZAL DO NORTE',
            'CEDRAL',
            'CODÓ',
            'COELHO NETO',
            'DAVINÓPOLIS',
            'DOM PEDRO',
            'DUQUE BACELAR',
            'ESPERANTINÓPOLIS',
            'ESTREITO',
            'FORMOSA DA SERRA NEGRA',
            'FORTALEZA DOS NOGUEIRAS',
            'GODOFREDO VIANA',
            'GOVERNADOR ARCHER',
            'GOVERNADOR EDISON LOBÃO',
            'GOVERNADOR EUGÊNIO BARROS',
            'GOVERNADOR NEWTON BELLO',
            'GRAÇA ARANHA',
            'GRAJAÚ',
            'GUIMARÃES',
            'IGARAPÉ DO MEIO',
            'IGARAPÉ GRANDE',
            'ITAPAVA DO GRAJAÚ',
            'ITAPECURU MIRIM',
            'JENIPAPO DOS VIEIRAS',
            'JOSELÂNDIA',
            'LAGO DO JUNCO',
            'LAGO DA PEDRA',
            'LAGO VERDE',
            'LAGOA GRANDE',
            'LAJEADO NOVO',
            'LIMA CAMPOS',
            'LORETO',
            'MATA ROMA',
            'MATINHA',
            'MILAGRES DO MARANHÃO',
            'MIRADOR',
            'MIRANDA DO NORTE',
            'MIRINZAL',
            'MONÇÃO',
            'MONTES ALTOS',
            "OLHO D'ÁGUA DAS CUNHÃS",
            'PALMEIRÂNDIA',
            'PARAIBANO',
            'PARNARAMA',
            'PASSAGEM FRANCA',
            'PASTOS BONS',
            'PAULINO NEVES',
            'PAULO RAMOS',
            'PEDRO DO ROSÁRIO',
            'PERITORÓ',
            'PINHEIRO',
            'PIO XII',
            'PORTO FRANCO',
            'PRESIDENTE DUTRA',
            'PRESIDENTE SARNEY',
            'RAPOSA',
            'RIACHÃO',
            'SAMBAÍBA',
            'SANTA INÊS',
            'SANTA LUZIA',
            'SANTA QUITÉRIA DO MA',
            'SANTA RITA',
            'SANTO ANTÔNIO DOS LOPES',
            'SÃO BERNARDO',
            'SÃO DOMINGOS DO AZEITÃO',
            'SÃO DOMINGOS DO MARANHÃO',
            'SÃO FRANCISCO DO BREJÃO',
            'SÃO FRANCISCO DO MARANHÃO',
            'SÃO JOÃO BATISTA',
            'SÃO JOÃO DO PARAÍSO',
            'SÃO JOÃO DO SOTER',
            'SÃO JOÃO DOS PATOS',
            'SÃO JOSÉ DE RIBAMAR',
            'SÃO JOSÉ DOS BASÍLIOS',
            'SÃO RAIMUNDO DO DOCA BEZERRA',
            'SÃO RAIMUNDO DAS MANGABEIRAS',
            'SATUBINHA',
            'SENADOR LA ROQUE',
            'SERRANO DO MARANHÃO',
            'SÍTIO NOVO',
            'SUCUPIRA DO NORTE',
            'TASSO FRAGOSO',
            'TRIZIDELA DO VALE',
            'TUNTUM',
            'TURIAÇU (SAAE-TURIAÇU)',
            'VITÓRIA DO MEARIM',
            'VITORINO FREIRE',
            'ZÉ DOCA',
        ],
        ESPECIAL: [
            'ESTADO DO MARANHÃO',
            'ARAIOSES',
            'ARAME',
            'BACABEIRA',
            'BARREIRINHAS',
            'BEQUIMÃO',
            'BURITICUPU',
            'CAROLINA',
            'CONCEIÇÃO DO LAGO-AÇU',
            'COROATÁ',
            'CURURUPU',
            'GONÇALVES DIAS',
            'GOVERNADOR ARCHER',
            'IMPERATRIZ',
            'JOÃO LISBOA',
            'MAGALHÃES DE ALMEIDA',
            'NOVA IORQUE',
            'PAÇO DO LUMIAR',
            'PALMEIRÂNDIA',
            'PENALVA',
            'PINDARÉ-MIRIM',
            'POÇÃO DE PEDRAS',
            'SÃO BENEDITO DO RIO PRETO',
            'SÃO BENTO',
            'SÃO LUÍS',
            'SÃO LUÍS GONZAGA DO MARANHÃO',
            'SÃO PEDRO DOS CRENTES',
            'SÃO VICENTE FÉRRER',
            'TIMBIRAS',
            'TIMON',
            'TUFILÂNDIA',
            'VARGEM GRANDE',
            'VIANA',
        ],
    },
    MT: {
        COMUM: [
            'Acorizal',
            'Água Boa',
            'Alto Araguaia',
            'Alto Boa Vista',
            'Alto Garças',
            'Alto Taquari',
            'Apiacás',
            'Araguaiana',
            'Arenápolis',
            'Aripuanã',
            'Barão de Melgaço',
            'Barra do Bugres',
            'BARRA-PREVI - Fundo Municipal de Previdência Social dos Servidores de Barra do Bugres',
            'Bom Jesus do Araguaia',
            'Brasnorte',
            'Campo Novo do Parecis',
            'Campo Verde',
            'Campos de Júlio',
            'Carlinda',
            'Castanheira',
            'Colíder',
            'Comodoro',
            'Cotriguaçu',
            'Curvelândia',
            'DAE/VG',
            'Denise',
            'Feliz Natal',
            "Figuerópolis D'Oeste",
            'Fundação Assistencial de Chapada dos Guimarães',
            'Fundo de Previdência Social dos Servidores de Confresa - PREVICON',
            'Fundo Municipal de Previdência Social dos Servidores de Nova Lacerda',
            'Fundo Municipal de Previdência Social dos Servidores Públicos de Planalto da Serra - IMPAS',
            'Fundo Municipal de Previdência Social dos Servidores Públicos de Tabaporã - PREVIPORA',
            'Fundo Municipal de Previdência Social - PREVI-NOBRES',
            'Fundo Municipal de Previdência Social - PREVINX',
            'Fundo Único Municipal de Educação de Cuiabá - FUNED',
            'Gaúcha do Norte',
            'General Carneiro',
            'Guarantã do Norte',
            'Guiratinga',
            'INSS',
            'Instituto Municipal de Previdênncia Social dos Servidores de Lucas do Rio Verde - PREVILUCAS',
            'Itanhangá',
            'Jaciara',
            'Juara',
            'Juína',
            'Juruena',
            'Juscimeira',
            'Lucas do Rio Verde',
            'Luciara',
            'Matupá',
            'NOSSA-PREVI - Instituto de Previdência Social dos Servidores Municipais de Nossa Senhora do Livramento',
            'Nossa Senhora do Livramento',
            'Nova Bandeirantes',
            'Nova Canaã do Norte',
            'Nova Lacerda',
            'Nova Maringá',
            'Nova Monte Verde',
            'Nova Mutum',
            'Nova Nazaré',
            'Nova Olímpia',
            'Nova Ubiratã',
            'Nova Xavantina',
            'Novo Horizonte do Norte',
            'Novo São Joaquim',
            'Paranaíta',
            'Planalto da Serra',
            'Pontal do Araguaia',
            'Ponte Branca',
            'Pontes e Lacerda',
            'Porto Alegre do Norte',
            'Porto dos Gaúchos',
            'Porto Esperidião',
            'Porto Estrela',
            'Poxoréu',
            'PREVI-SERV-Chapada dos Guimarães',
            'PREVISO-Sorriso',
            'PREVIVAG-Várzea Grande',
            'PREV-JACI - Fundo Municipal de Previdência Social dos Servidores de Jaciara',
            'Primavera do Leste',
            'Querência',
            'Reserva do Cabaçal',
            'Ribeirão Cascalheira',
            'Ribeirãozinho',
            'Rio Branco',
            'Salto do Céu',
            'SAMAE - Serviço Autônomo de Água e Esgoto de Tangará da Serra',
            'Santa Terezinha',
            'Santo Afonso',
            'São José do Rio Claro',
            'São José dos Quatro Marcos',
            'São José do Xingu',
            'São Pedro da Cipa',
            'SANEAR - Serviço de Saneamento Ambiental de Rondonópolis',
            'Sapezal',
            'SAAES - Serviço Autônomo de Água e Esgoto de Sinop',
            "SAEMI - Mirassol D'Oeste",
            'SERRA-PREV',
            'Sinop',
            'Sorriso',
            'Tabaporã',
            'Tangará da Serra',
            'Tapurah',
            'Terra Nova do Norte',
            'Tesouro',
            'Torixoréu',
            'Vale de São Domingos',
            'Vera',
            'Vila Rica',
        ],
        ESPECIAL: [
            'Estado de Mato Grosso',
            'DETRAN',
            'INDEA',
            'INTERMAT',
            'JUCEMAT',
            'MT PREV',
            'MT SAÚDE',
            'UNEMAT',
            'Alta Floresta',
            'Alto Paraguai',
            'Araguainha',
            'Araputanga',
            'Barra do Garças',
            'Cáceres',
            'Campinápolis',
            'Canabrava do Norte',
            'Canarana',
            'Chapada dos Guimarães',
            'Cláudia',
            'Confresa',
            'Cuiabá',
            'Diamantino',
            'Dom Aquino',
            'Itaúba',
            'Itiquira',
            'Jauru',
            "Lambari D'Oeste",
            "Mirassol D'Oeste",
            'Nobres',
            'Nova Brasilândia',
            'Paranatinga',
            'Pedra Preta',
            'Peixoto de Azevedo',
            'Poconé',
            'Rondonópolis',
            'Rosário Oeste',
            'Santo Antônio de Leverger',
            'Várzea Grande',
        ],
    },
    MS: {
        COMUM: [
            'ESTADO DE MATO GROSSO DO SUL',
            'AGÊNCIA ESTADUAL DE GESTÃO DE EMPREENDIMENTOS DO MATO GROSSO DO SUL – AGESUL',
            'DEPARTAMENTO ESTADUAL DE TRÂNSITO DE MATO GROSSO DO SUL – DETRAN',
            'FUNDAÇÃO DE TURISMO DE MATO GROSSO DO SUL – FUNDTUR',
            'FUNDAÇÃO SERVIÇOS DE SAÚDE DO ESTADO DE MATO GROSSO DO SUL - FUNSAU',
            'FUNDAÇÃO UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL - UEMS',
            'EMPRESA DE SANEAMENTO DE MATO GROSSO DO SUL SA – SANESUL',
            'MUNICÍPIO DE APARECIDA DO TABOADO',
            'FUNDAÇÃO ESTATAL DE SAÚDE DE APARECIDA DO TABOADO – FESAT (Mun Aparecida do Taboado)',
            'MUNICÍPIO DE AQUIDAUANA',
            'MUNICÍPIO DE BATAGUASSU',
            'MUNICÍPIO DE BELA VISTA',
            'MUNICÍPIO DE CAMPO GRANDE',
            'AGÊNCIA MUNICIPAL DE TECNOLOGIA DA INFORMAÇÃO E INOVAÇÃO (Mun Campo Grande)',
            'MUNICÍPIO DE CASSILÂNDIA',
            'MUNICÍPIO DE CHAPADÃO DO SUL',
            'FUNDAÇÃO ESTATAL DE SAÚDE DO PANTANAL – FESP (Município de Coxim)',
            'MUNICÍPIO DE DOURADOS',
            'FUNDAÇÃO DE SERVIÇOS DE SAÚDE DE DOURADOS – FUNSAUD (Município de Dourados)',
            'MUNICÍPIO DE JUTI',
            'MUNICÍPIO DE PONTA PORÃ',
            'MUNICÍPIO DE PORTO MURTINHO',
            'MUNICÍPIO DE RIO BRILHANTE',
            'FUNDAÇÃO DE SAÚDE DO MUNICÍPIO DE SÃO GABRIEL DO OESTE (Mun São Gabriel do Oeste)',
            'MUNICÍPIO DE SELVÍRIA',
            'MUNICÍPIO DE TRÊS LAGOAS',
        ],
        ESPECIAL: [
            'AUTARQUIA MUNICIPAL DE TRÂNSITO E CIDADANIA - AMC',
            'FUNDAÇÃO DE PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS MUNICIPAIS DE MUNDO NOVO - FUNPREMN',
            'MUNICÍPIO DE FORTALEZA',
            'MUNICÍPIO DE MUNDO NOVO',
            'MUNICÍPIO DE PEDRO GOMES',
            'MUNICÍPIO DE PORTO NACIONAL',
            'MUNICIPIO DE ROSANA - SP',
        ],
    },
    MG: {
        COMUM: [
            'CONSORCIO INST. DE COOPERAÇÃO INTERMUNICIPAL DO M. PARAOPEBA',
            'MUNICÍPIO DE ABADIA DOS DOURADOS',
            'MUNICÍPIO DE AÇUCENA',
            'MUNICÍPIO DE ÁGUA COMPRIDA',
            'MUNICÍPIO DE AGUANIL',
            'MUNICÍPIO DE ÁGUAS FORMOSAS',
            'MUNICÍPIO DE AIMORÉS',
            'MUNICÍPIO DE ALÉM PARAÍBA',
            'MUNICÍPIO DE ALFREDO VASCONCELOS',
            'MUNICÍPIO DE ALMENARA',
            'MUNICÍPIO DE ALTEROSA',
            'MUNICÍPIO DE ALTO CAPARAÓ',
            'MUNICÍPIO DE ALTO JEQUITIBÁ',
            'MUNICÍPIO DE ALTO RIO DOCE',
            'MUNICÍPIO DE ALVARENGA',
            'MUNICÍPIO DE ALVINÓPOLIS',
            'CÂMARA MUNICIPAL DE ALVINÓPOLIS',
            'MUNICÍPIO DE ALVORADA DE MINAS',
            'MUNICÍPIO DE AMPARO DA SERRA',
            'MUNICÍPIO DE ANDRADAS',
            'MUNICÍPIO DE ANDRELÂNDIA',
            'MUNICÍPIO DE ANGELÂNDIA',
            'MUNICÍPIO DE ANTÔNIO CARLOS',
            'MUNICÍPIO DE ANTÔNIO DIAS',
            'MUNICÍPIO DE ARAÇAÍ',
            'MUNICÍPIO DE ARACITABA',
            'MUNICÍPIO DE ARAÇUAÍ',
            'MUNICÍPIO DE ARAGUARI',
            'SAE - SUPERINTENDÊNCIA DE ÁGUA E ESGOTO',
            'MUNICÍPIO DE ARANTINA',
            'MUNICÍPIO DE ARAPONGA',
            'MUNICÍPIO DE ARAPORÃ',
            'MUNICÍPIO DE ARAÚJOS',
            'MUNICÍPIO DE ARCEBURGO',
            'MUNICÍPIO DE ARCOS',
            'FUNDO MUNICIPAL DE SAÚDE',
            'MUNICÍPIO DE AREADO',
            'MUNICÍPIO DE ARGIRITA',
            'MUNICÍPIO DE ARICANDUVA',
            'MUNICÍPIO DE ARINOS',
            'MUNICÍPIO DE ASTOLFO DUTRA',
            'MUNICÍPIO DE AUGUSTO DE LIMA',
            'MUNICÍPIO DE BAEPENDI',
            'MUNICÍPIO DE BALDIM',
            'MUNICÍPIO DE BAMBUÍ',
            'MUNICÍPIO DE BANDEIRA',
            'MUNICÍPIO DE BANDEIRA DO SUL',
            'MUNICÍPIO DE BARÃO DE COCAIS',
            'CÂMARA MUNICIPAL DE BARÃO DE COCAIS',
            'MUNICÍPIO DE BARÃO DO MONTE ALTO',
            'MUNICÍPIO DE BARBACENA',
            'CENATUR - EMPRESA MUNICIPAL DE TURISMO DE BARBACENA',
            'SIMPAS- SISTEMA MUN. PREVIDÊNCIA E ASSISTÊNCIA AO SERVIDOR',
            'DEMASA - DEPARTAMENTO MUNICIPAL DE MEIO AMBIENTE E SANEAMENTO',
            'DEPARTAMENTO MUNICIPAL DE SAÚDE PÚBLICA - DEMASP',
            'DEMAE - DEPARTAMENTO MUNICIPAL DE ÁGUA E ESGOTO',
            'MUNICÍPIO DE BARRA LONGA',
            'MUNICÍPIO DE BELA VISTA DE MINAS',
            'MUNICÍPIO DE BELMIRO BRAGA',
            'MUNICÍPIO DE BELO VALE',
            'MUNICÍPIO DE BERILO',
            'MUNICÍPIO DE BIAS FORTES',
            'MUNICÍPIO DE BICAS',
            'MUNICÍPIO DE BIQUINHAS',
            'MUNICÍPIO DE BOA ESPERANÇA',
            'IPREMBE - INSTITUTO DE PREVIDÊNCIA DO MUNICÍPIO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE BOA ESPERANÇA',
            'MUNICÍPIO DE BOCAIÚVA',
            'HOSPITAL MUNICIPAL DR. GIL ALVES',
            'INSTITUTO MUN. DOS SERVIDORES PUBLICOS DE BOCAIUVA',
            'MUNICÍPIO DE BOM DESPACHO',
            'MUNICÍPIO DE BOM JARDIM DE MINAS',
            'MUNICÍPIO DE BOM JESUS DA PENHA',
            'CÂMARA MUNICIPAL DE BOM JESUS DA PENHA',
            'MUNICÍPIO DE BOM JESUS DO AMPARO',
            'MUNICÍPIO DE BOM JESUS DO GALHO',
            'MUNICÍPIO DE BOM REPOUSO',
            'MUNICÍPIO DE BOM SUCESSO',
            'INST.DE PREV.DOS SERVIDORES PUBLICOS MUNICIPAIS B.SUCESSO',
            'MUNICÍPIO DE BONFIM',
            'MUNICÍPIO DE BONFINÓPOLIS DE MINAS',
            'MUNICÍPIO DE BONITO DE MINAS',
            'MUNICÍPIO DE BORDA DA MATA',
            'MUNICÍPIO DE BOTELHOS',
            'MUNICÍPIO DE BOTUMIRIM',
            'MUNICÍPIO DE BRÁS PIRES',
            'MUNICÍPIO DE BRASÍLIA DE MINAS',
            'MUNICÍPIO DE BRAÚNAS',
            'MUNICÍPIO DE BRAZÓPOLIS',
            'MUNICÍPIO DE BRUMADINHO',
            'MUNICÍPIO DE BUENÓPOLIS',
            'MUNICÍPIO DE BURITIS',
            'MUNICÍPIO DE CABECEIRA GRANDE',
            'MUNICÍPIO DE CACHOEIRA DA PRATA',
            'MUNICÍPIO DE CACHOEIRA DE MINAS',
            'MUNICÍPIO DE CACHOEIRA DE PAJEÚ',
            'MUNICÍPIO DE CACHOEIRA DOURADA',
            'MUNICÍPIO DE CAETANÓPOLIS',
            'MUNICÍPIO DE CAIANA',
            'MUNICÍPIO DE CAJURI',
            'MUNICÍPIO DE CALDAS',
            'MUNICÍPIO DE CAMACHO',
            'MUNICÍPIO DE CAMANDUCAIA',
            'MUNICÍPIO DE CAMBUÍ',
            'FUNDO DE APOSENTADORIA E PENSÃO DO SERV PÚB MUNICIPAL',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE CAMBUÍ',
            'MUNICÍPIO DE CAMBUQUIRA',
            'MUNICÍPIO DE CAMPANÁRIO',
            'REGIME PROPRIO DE PREV. SOCIAL DO M. DE CAMPANARIO',
            'MUNICÍPIO DE CAMPANHA',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS',
            'MUNICÍPIO DE CAMPESTRE',
            'MUNICÍPIO DE CAMPINA VERDE',
            'MUNICÍPIO DE CAMPO AZUL',
            'MUNICÍPIO DE CAMPO DO MEIO',
            'MUNICÍPIO DE CAMPO FLORIDO',
            'MUNICÍPIO DE CAMPOS GERAIS',
            'INST. DE PREVIDENCIA DOS SERV. PUBLICOS DE CAMPOS  GERAIS',
            'MUNICÍPIO DE CANAÃ',
            'MUNICÍPIO DE CANÁPOLIS',
            'MUNICÍPIO DE CANTAGALO',
            'INST DE PREVIDENCIA DOS SERVIDORES PUBLICOS DE CANTAGALO',
            'MUNICÍPIO DE CAPARAÓ',
            'MUNICÍPIO DE CAPELA NOVA',
            'MUNICÍPIO DE CAPETINGA',
            'MUNICÍPIO DE CAPIM BRANCO',
            'MUNICÍPIO DE CAPINÓPOLIS',
            'MUNICÍPIO DE CAPITÃO ENÉAS',
            'MUNICÍPIO DE CARAÍ',
            'MUNICÍPIO DE CARANAÍBA',
            'MUNICÍPIO DE CARANDAÍ',
            'FUNDO DE APOSENTADORIA E PENSÃO DO SERV PÚB MUNICIPAL',
            'HOSPITAL MUNICIPAL SANTANA DE CARANDAÍ',
            'MUNICÍPIO DE CARATINGA',
            'MUNICÍPIO DE CARBONITA',
            'MUNICÍPIO DE CARLOS CHAGAS',
            'MUNICÍPIO DE CARMO DA CACHOEIRA',
            'MUNICÍPIO DE CARMO DE MINAS',
            'MUNICÍPIO DE CARMO DO CAJURU',
            'MUNICÍPIO DE CARMO DO PARANAÍBA',
            'MUNICÍPIO DE CARMO DO RIO CLARO',
            'MUNICÍPIO DE CARMÓPOLIS DE MINAS',
            'MUNICÍPIO DE CARVALHÓPOLIS',
            'MUNICÍPIO DE CARVALHOS',
            'MUNICÍPIO DE CASA GRANDE',
            'MUNICÍPIO DE CASCALHO RICO',
            'MUNICÍPIO DE CÁSSIA',
            'MUNICÍPIO DE CATAS ALTAS',
            'MUNICÍPIO DE CATAS ALTAS DA NORUEGA',
            'MUNICÍPIO DE CATUJI',
            'MUNICÍPIO DE CAXAMBU',
            'MUNICÍPIO DE CEDRO DO ABAETÉ',
            'MUNICÍPIO DE CENTRAL DE MINAS',
            'MUNICÍPIO DE CHÁCARA',
            'MUNICÍPIO DE CHALÉ',
            'MUNICÍPIO DE CHAPADA DO NORTE',
            'MUNICÍPIO DE CHAPADA GAÚCHA',
            'MUNICÍPIO DE CHIADOR',
            'MUNICÍPIO DE CIPOTÂNEA',
            'MUNICÍPIO DE CLARAVAL',
            'MUNICÍPIO DE CLARO DOS POÇÕES',
            'MUNICÍPIO DE CLÁUDIO',
            'MUNICÍPIO DE COIMBRA',
            'MUNICÍPIO DE COLUNA',
            'MUNICÍPIO DE COMENDADOR GOMES',
            'MUNICÍPIO DE COMERCINHO',
            'MUNICÍPIO DE CONCEIÇÃO DA APARECIDA',
            'MUNICÍPIO DE CONCEIÇÃO DA BARRA DE MINAS',
            'MUNICÍPIO DE CONCEIÇÃO DAS ALAGOAS',
            'MUNICÍPIO DE CONCEIÇÃO DE IPANEMA',
            'MUNICÍPIO DE CONCEIÇÃO DO MATO DENTRO',
            'MUNICÍPIO DE CONCEIÇÃO DO RIO VERDE',
            'MUNICÍPIO DE CONCEIÇÃO DOS OUROS',
            'MUNICÍPIO DE CÔNEGO MARINHO',
            'MUNICÍPIO DE CONFINS',
            'MUNICÍPIO DE CONGONHAL',
            'MUNICÍPIO DE CONGONHAS',
            'INSTITUTO MUNICIPAL DE SEGURIDADE SOCIAL',
            'FUNDAÇÃO MUNICIPAL DE CULTURA, LAZER E TURISMO',
            'FUNDAÇÃO MUNICIPAL DE SAÚDE - PRÓ-SAÚDE',
            'PREVIDENCIA DO MUNICIPIO DE CONGONHAS',
            'MUNICÍPIO DE CONGONHAS DO NORTE',
            'MUNICÍPIO DE CONQUISTA',
            'MUNICÍPIO DE CONSOLAÇÃO',
            'MUNICÍPIO DE COQUEIRAL',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE COQUEIRAL',
            'MUNICÍPIO DE CORAÇÃO DE JESUS',
            'INST. DE PREV.SOCIAL DO MUN.CORAÇÃO DE JESUS - PREVCOR',
            'HOSPITAL MUN. SÃO VICENTE DE PAULO',
            'MUNICÍPIO DE CORDISBURGO',
            'MUNICÍPIO DE CORDISLÂNDIA',
            'MUNICÍPIO DE CORINTO',
            'MUNICÍPIO DE COROMANDEL',
            'MUNICÍPIO DE CORONEL FABRICIANO',
            'FUNASF - FUND. DE AÇÃO SOCIAL FABRICIANENSE',
            'MUNICÍPIO DE CORONEL MURTA',
            'MUNICÍPIO DE CÓRREGO DANTA',
            'MUNICÍPIO DE CÓRREGO FUNDO',
            'MUNICÍPIO DE CÓRREGO NOVO',
            'MUNICÍPIO DE COUTO DE MAGALHÃES DE MINAS',
            'MUNICÍPIO DE CRISTAIS',
            'MUNICÍPIO DE CRISTÁLIA',
            'MUNICÍPIO DE CRISTIANO OTÔNI',
            'MUNICÍPIO DE CRISTINA',
            'MUNICÍPIO DE CRUCILÂNDIA',
            'MUNICÍPIO DE CRUZEIRO DA FORTALEZA',
            'INST.DE PREVIDENCIA MUNICIPAL DE CRUZEIRODA FORTALEZA',
            'MUNICÍPIO DE CRUZÍLIA',
            'MUNICÍPIO DE CUPARAQUE',
            'MUNICÍPIO DE CURVELO',
            'MUNICÍPIO DE DATAS',
            'MUNICÍPIO DE DELFIM MOREIRA',
            'CÂMARA MUNICIPAL DE DELFIM MOREIRA',
            'MUNICÍPIO DE DELTA',
            'MUNICÍPIO DE DESCOBERTO',
            'MUNICÍPIO DE DESTERRO DE ENTRE-RIOS',
            'MUNICÍPIO DE DESTERRO DO MELO',
            'MUNICÍPIO DE DIAMANTINA',
            'FUMPREV - FUNDO DE PREV. DO MUN. DE DIAMANTINA',
            'MUNICÍPIO DE DIOGO DE VASCONCELOS',
            'MUNICÍPIO DE DIONÍSIO',
            'MUNICÍPIO DE DIVINÉSIA',
            'MUNICÍPIO DE DIVINO',
            'MUNICÍPIO DE DIVINO DAS LARANJEIRAS',
            'MUNICÍPIO DE DIVINOLÂNDIA DE MINAS',
            'MUNICÍPIO DE DIVISA NOVA',
            'MUNICÍPIO DE DIVISÓPOLIS',
            'MUNICÍPIO DE DOM CAVATI',
            'MUNICÍPIO DE DOM JOAQUIM',
            'MUNICÍPIO DE DONA EUSÉBIA',
            'MUNICÍPIO DE DORES DE CAMPOS',
            'MUNICÍPIO DE DORES DO INDAIÁ',
            'MUNICÍPIO DE DORES DO TURVO',
            'MUNICÍPIO DE DORESÓPOLIS',
            'MUNICÍPIO DE DOURADOQUARA',
            'MUNICÍPIO DE DURANDÉ',
            'MUNICÍPIO DE ELÓI MENDES',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE ELÓI MENDES',
            'MUNICÍPIO DE ENGENHEIRO CALDAS',
            'MUNICÍPIO DE ENTRE-RIOS DE MINAS',
            'MUNICÍPIO DE ERVÁLIA',
            'MUNICÍPIO DE ESMERALDAS',
            'MUNICÍPIO DE ESPERA FELIZ',
            'MUNICÍPIO DE ESTRELA DO INDAIÁ',
            'MUNICÍPIO DE EUGENÓPOLIS',
            'MUNICÍPIO DE EWBANK DA CÂMARA',
            'MUNICÍPIO DE EXTREMA',
            'INST. DE PREVIDENCIA DO MUNICIPIO EXTREMA- PREVEXTREMA',
            'MUNICÍPIO DE FAMA',
            'MUNICÍPIO DE FARIA LEMOS',
            'MUNICÍPIO DE FELÍCIO DOS SANTOS',
            'MUNICÍPIO DE FELISBURGO',
            'MUNICÍPIO DE FELIXLÂNDIA',
            'INSTITUTO DE PREVIDENCIA MUNICIPAL DE FELIXLANDIA',
            'MUNICÍPIO DE FERNANDES TOURINHO',
            'MUNICÍPIO DE FERROS',
            'MUNICÍPIO DE FERVEDOURO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE FERVEDOURO',
            'MUNICÍPIO DE FLORESTAL',
            'MUNICÍPIO DE FORMIGA',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE FORMIGA',
            'PREVIFOR - INSTITUTO DE PREV. DOS SERV. PÚBLICOS MUNICIPAIS',
            'MUNICÍPIO DE FORMOSO',
            'MUNICÍPIO DE FORTALEZA DE MINAS',
            'MUNICÍPIO DE FRANCISCO BADARÓ',
            'MUNICÍPIO DE FRANCISCO DUMONT',
            'MUNICÍPIO DE FRANCISCO SÁ',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE FRANCISCO SÁ',
            'MUNICÍPIO DE FRANCISCÓPOLIS',
            'MUNICÍPIO DE FREI GASPAR',
            'MUNICÍPIO DE FREI INOCÊNCIO',
            'MUNICÍPIO DE FREI LAGONEGRO',
            'MUNICÍPIO DE FRONTEIRA',
            'MUNICÍPIO DE FRONTEIRA DOS VALES',
            'MUNICÍPIO DE FRUTA DE LEITE',
            'MUNICÍPIO DE FRUTAL',
            'MUNICÍPIO DE FUNILÂNDIA',
            'MUNICÍPIO DE GALILÉIA',
            'MUNICÍPIO DE GLAUCILÂNDIA',
            'MUNICÍPIO DE GOIABEIRA',
            'MUNICÍPIO DE GONÇALVES',
            'MUNICÍPIO DE GONZAGA',
            'MUNICÍPIO DE GOVERNADOR VALADARES',
            'FUNSEC - FUNDAÇÃO SERVIÇOS DE EDUCAÇÃO E CULTURA',
            'FUSHOSP - FUND. SERV. HOSPITALAR',
            'FUSOBRAS - FUND. SERV. OBRAS SOCIAIS',
            'IPREM/GV - INSTITUTO DE PREV. MUNICIPAL DE GOV. VALADARES',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE GOVERNADOR VALADARES',
            'SEMOV - SERV. MUN. DE OBRAS E VIAÇÃO',
            'MUNICÍPIO DE GRUPIARA',
            'MUNICÍPIO DE GUANHÃES',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE GUANHÃES',
            'MUNICÍPIO DE GUAPÉ',
            'MUNICÍPIO DE GUARACIAMA',
            'MUNICÍPIO DE GUARANI',
            'MUNICÍPIO DE GUARARÁ',
            'MUNICÍPIO DE GUARDA-MOR',
            'MUNICÍPIO DE GUAXUPÉ',
            'MUNICÍPIO DE GUIDOVAL',
            'MUNICÍPIO DE GUIMARÂNIA',
            'MUNICÍPIO DE GUIRICEMA',
            'FUNDO MUN. DE PREV.DOS SERVIDORES PUBLICOS DE GUIRICEMA',
            'MUNICÍPIO DE IAPU',
            'MUNICÍPIO DE IBIRACI',
            'CÂMARA MUNICIPAL DE IBIRACI',
            'MUNICÍPIO DE IBIRITÉ',
            'MUNICÍPIO DE IBITIÚRA DE MINAS',
            'MUNICÍPIO DE ICARAÍ DE MINAS',
            'MUNICÍPIO DE IGARAPÉ',
            'MUNICÍPIO DE IGARATINGA',
            'MUNICÍPIO DE IJACI',
            'MUNICÍPIO DE ILICÍNEA',
            'MUNICÍPIO DE IMBÉ DE MINAS',
            'MUNICÍPIO DE INCONFIDENTES',
            'MUNICÍPIO DE INDAIABIRA',
            'MUNICÍPIO DE INDIANÓPOLIS',
            'MUNICÍPIO DE INGAÍ',
            'MUNICÍPIO DE INHAPIM',
            'MUNICÍPIO DE IPABA',
            'MUNICÍPIO DE IPIAÇU',
            'IPREMIP - INST. DE PREVIDENCIA MUNICIPAL DE IPIAÇU',
            'MUNICÍPIO DE IPUIÚNA',
            'AUTARQUIA MUNICIPAL DE ENSINO',
            'MUNICÍPIO DE IRAÍ DE MINAS',
            'MUNICÍPIO DE ITABIRINHA',
            'MUNICÍPIO DE ITABIRITO',
            'MUNICÍPIO DE ITACAMBIRA',
            'MUNICÍPIO DE ITACARAMBI',
            'MUNICÍPIO DE ITAGUARA',
            'MUNICÍPIO DE ITAIPÉ',
            'MUNICÍPIO DE ITAJUBÁ',
            'CÂMARA MUNICIPAL DE ITAJUBÁ',
            'MUNICÍPIO DE ITAMARANDIBA',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS',
            'MUNICÍPIO DE ITAMARATI DE MINAS',
            'MUNICÍPIO DE ITAMBACURI',
            'MUNICÍPIO DE ITAMBÉ DO MATO DENTRO',
            'MUNICÍPIO DE ITAMOJI',
            'MUNICÍPIO DE ITANHANDU',
            'MUNICÍPIO DE ITANHOMI',
            'MUNICÍPIO DE ITAOBIM',
            'MUNICÍPIO DE ITAPAGIPE',
            'IPREVI - INSTITUTO DE PREV. DOS SERV. PUB.MUNICIPAIS',
            'MUNICÍPIO DE ITAPECERICA',
            'MUNICÍPIO DE ITAPEVA',
            'MUNICÍPIO DE ITATIAIUÇU',
            'MUNICÍPIO DE ITAÚ DE MINAS',
            'MUNICÍPIO DE ITAÚNA',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE ITAÚNA',
            'IMP - INSTITUTO MUNIC.PREV.SERV.PÚBLICOS DE ITAÚNA',
            'MUNICÍPIO DE ITAVERAVA',
            'MUNICÍPIO DE ITINGA',
            'MUNICÍPIO DE ITUETA',
            'MUNICÍPIO DE ITUMIRIM',
            'MUNICÍPIO DE ITURAMA',
            'CÂMARA MUNICIPAL DE ITURAMA',
            'MUNICÍPIO DE ITUTINGA',
            'MUNICÍPIO DE JABOTICATUBAS',
            'MUNICÍPIO DE JACINTO',
            'CÂMARA MUNICIPAL DE JACINTO',
            'MUNICÍPIO DE JACUÍ',
            'MUNICÍPIO DE JACUTINGA',
            'MUNICÍPIO DE JAGUARAÇU',
            'MUNICÍPIO DE JAÍBA',
            'MUNICÍPIO DE JAMPRUCA',
            'MUNICÍPIO DE JANUÁRIA',
            'INSTITUTO DE PREVIDENCIA MUNICIPAL DE JANUARIA',
            'MUNICÍPIO DE JAPARAÍBA',
            'MUNICÍPIO DE JAPONVAR',
            'MUNICÍPIO DE JECEABA',
            'MUNICÍPIO DE JENIPAPO DE MINAS',
            'MUNICÍPIO DE JEQUERI',
            'MUNICÍPIO DE JEQUITIBÁ',
            'MUNICÍPIO DE JEQUITINHONHA',
            'MUNICÍPIO DE JESUÂNIA',
            'MUNICÍPIO DE JOAÍMA',
            'MUNICÍPIO DE JOÃO PINHEIRO',
            'MUNICÍPIO DE JORDÂNIA',
            'MUNICÍPIO DE JOSÉ RAYDAN',
            'MUNICÍPIO DE JOSENÓPOLIS',
            'MUNICÍPIO DE JUATUBA',
            'MUNICÍPIO DE JUIZ DE FORA',
            'DEMLURB - DEPTO MUNIC. LIMPEZA URBANA',
            'MUNICÍPIO DE JURAMENTO',
            'MUNICÍPIO DE JURUAIA',
            'MUNICÍPIO DE JUVENÍLIA',
            'MUNICÍPIO DE LADAINHA',
            'MUNICÍPIO DE LAGAMAR',
            'MUNICÍPIO DE LAGOA DA PRATA',
            'MUNICÍPIO DE LAGOA DOS PATOS',
            'MUNICÍPIO DE LAGOA DOURADA',
            'MUNICÍPIO DE LAGOA FORMOSA',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE LAGOA FORMOSA',
            'MUNICÍPIO DE LAGOA GRANDE',
            'MUNICÍPIO DE LAGOA SANTA',
            'MUNICÍPIO DE LAMBARI',
            'MUNICÍPIO DE LAMIM',
            'MUNICÍPIO DE LARANJAL',
            'FUNDO MUNICIPAL DE SAÚDE',
            'MUNICÍPIO DE LASSANCE',
            'MUNICÍPIO DE LEANDRO FERREIRA',
            'MUNICÍPIO DE LIBERDADE',
            'MUNICÍPIO DE LIMA DUARTE',
            'DEMAE - DEPARTAMENTO MUNICIPAL DE ÁGUA E ESGOTO',
            'MUNICÍPIO DE LIMEIRA DO OESTE',
            'MUNICÍPIO DE LONTRA',
            'MUNICÍPIO DE LUISBURGO',
            'MUNICÍPIO DE LUISLÂNDIA',
            'MUNICÍPIO DE LUMINÁRIAS',
            'MUNICÍPIO DE LUZ',
            'MUNICÍPIO DE MACHACALIS',
            'MUNICÍPIO DE MACHADO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE MACHADO',
            'MUNICÍPIO DE MADRE DE DEUS DE MINAS',
            'MUNICÍPIO DE MALACACHETA',
            'MUNICÍPIO DE MAMONAS',
            'MUNICÍPIO DE MANGA',
            'MUNICÍPIO DE MANHUMIRIM',
            'MUNICÍPIO DE MANTENA',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE MANTENA',
            'MUNICÍPIO DE MARIA DA FÉ',
            'MUNICÍPIO DE MARIANA',
            'MUNICÍPIO DE MARILAC',
            'MUNICÍPIO DE MARIPÁ DE MINAS',
            'MUNICÍPIO DE MARLIÉRIA',
            'MUNICÍPIO DE MARTINS SOARES',
            'MUNICÍPIO DE MATA VERDE',
            'MUNICÍPIO DE MATERLÂNDIA',
            'MUNICÍPIO DE MATEUS LEME',
            'MUNICÍPIO DE MATIAS CARDOSO',
            'MUNICÍPIO DE MATIAS LOBATO',
            'MUNICÍPIO DE MATIPÓ',
            'MUNICÍPIO DE MATO VERDE',
            'MUNICÍPIO DE MATOZINHOS',
            'MUNICÍPIO DE MEDEIROS',
            'MUNICÍPIO DE MERCÊS',
            'IPREME - INSTITUTO DE PREVIDÊNCIA MUNICIPAL DE MERCÊS',
            'MUNICÍPIO DE MINAS NOVAS',
            'MUNICÍPIO DE MINDURI',
            'MUNICÍPIO DE MIRABELA',
            'MUNICÍPIO DE MIRADOURO',
            'MUNICÍPIO DE MIRAÍ',
            'MUNICÍPIO DE MIRAVÂNIA',
            'MUNICÍPIO DE MOEDA',
            'MUNICÍPIO DE MONJOLOS',
            'MUNICÍPIO DE MONSENHOR PAULO',
            'MUNICÍPIO DE MONTALVÂNIA',
            'MUNICÍPIO DE MONTE ALEGRE DE MINAS',
            'MUNICÍPIO DE MONTE BELO',
            'IPSEMB - INSTITUTO PREV. DOS SERV. MUNICIPAIS DE MONTE BELO',
            'MUNICÍPIO DE MONTE CARMELO',
            'MUNICÍPIO DE MONTE FORMOSO',
            'MUNICÍPIO DE MONTE SANTO DE MINAS',
            'MUNICÍPIO DE MONTEZUMA',
            'MUNICÍPIO DE MORADA NOVA DE MINAS',
            'MUNICÍPIO DE MORRO DA GARÇA',
            'MUNICÍPIO DE MORRO DO PILAR',
            'MUNICÍPIO DE MUNHOZ',
            'MUNICÍPIO DE MUTUM',
            'MUNICÍPIO DE MUZAMBINHO',
            'MUNICÍPIO DE NACIP RAYDAN',
            'MUNICÍPIO DE NAQUE',
            'MUNICÍPIO DE NATALÂNDIA',
            'MUNICÍPIO DE NATÉRCIA',
            'MUNICÍPIO DE NEPOMUCENO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE NEPOMUCENO',
            'MUNICÍPIO DE NINHEIRA',
            'MUNICÍPIO DE NOVA BELÉM',
            'MUNICÍPIO DE NOVA ERA',
            'MUNICÍPIO DE NOVA MÓDICA',
            'MUNICÍPIO DE NOVA PONTE',
            'FUNDAÇÃO MUNICIPAL DE SAÚDE - PRÓ-SAÚDE',
            'MUNICÍPIO DE NOVA PORTEIRINHA',
            'MUNICÍPIO DE NOVA RESENDE',
            'MUNICÍPIO DE NOVA SERRANA',
            'FUNDO PREVIDENCIÁRIO DO MUNICÍPIO DE NOVA SERRANA',
            'MUNICÍPIO DE NOVA UNIÃO',
            'MUNICÍPIO DE NOVO CRUZEIRO',
            'MUNICÍPIO DE NOVO ORIENTE DE MINAS',
            'MUNICÍPIO DE NOVORIZONTE',
            "MUNICÍPIO DE OLHOS-D'ÁGUA",
            'MUNICÍPIO DE OLÍMPIO NORONHA',
            'MUNICÍPIO DE OLIVEIRA',
            'IMPASOL - INSTITUTO PREVIDÊNCIA MUNICIPAL',
            'CÂMARA MUNICIPAL DE OLIVEIRA',
            'MUNICÍPIO DE ONÇA DE PITANGUI',
            'MUNICÍPIO DE ORATÓRIOS',
            'MUNICÍPIO DE ORIZÂNIA',
            'MUNICÍPIO DE OURO BRANCO',
            'MUNICÍPIO DE OURO FINO',
            'DEP. MUN. AUTONOMO DE ÁGUA E ESGOTO OURO FINO',
            'MUNICÍPIO DE OURO PRETO',
            'MUNICÍPIO DE PAINEIRAS',
            'MUNICÍPIO DE PAINS',
            'MUNICÍPIO DE PAIVA',
            'MUNICÍPIO DE PALMA',
            'MUNICÍPIO DE PARÁ DE MINAS',
            'INSTITUTO DE PREVIDENCIA DOS SERV. PUB. DE PARÁ DE MINAS',
            'FUMUSA-FUNDAÇÃO MUNICIPAL DE SAÚDE HOSPITAL E PRONTO SOCORRO',
            'MUNICÍPIO DE PARACATU',
            'INSTITUTO DE PREVID. SOCIAL SERV. PÚBL. MUNICIPAIS',
            'SECRETARIA MUNICIPAL DE SAÚDE',
            'MUNICÍPIO DE PARAGUAÇU',
            'FUNDO PREVIDENCIARIO MUNICIPAL',
            'MUNICÍPIO DE PARAISÓPOLIS',
            'MUNICÍPIO DE PARAOPEBA',
            'INSTITUTO MUNICIPAL DE SEGURIDADE SOCIAL',
            'MUNICÍPIO DE PASSA TEMPO',
            'REGIME PROPRIO DE PREV. SOCIAL M. DE PASSA TEMPO',
            'MUNICÍPIO DE PASSABÉM',
            'MUNICÍPIO DE PASSA-QUATRO',
            'MUNICÍPIO DE PATOS DE MINAS',
            'INSTITUTO DE PREVIDÊNCIA DE PATOS DE MINAS - IPREM',
            'MUNICÍPIO DE PAULA CÂNDIDO',
            'MUNICÍPIO DE PAULISTAS',
            'MUNICÍPIO DE PAVÃO',
            'MUNICÍPIO DE PEÇANHA',
            'MUNICÍPIO DE PEDRA AZUL',
            'MUNICÍPIO DE PEDRA BONITA',
            'MUNICÍPIO DE PEDRA DO ANTA',
            'MUNICÍPIO DE PEDRALVA',
            'MUNICÍPIO DE PEDRAS DE MARIA DA CRUZ',
            'CÂMARA MUNICIPAL DE PEDRAS DE MARIA DA CRUZ',
            'MUNICÍPIO DE PEDRINÓPOLIS',
            'MUNICÍPIO DE PEDRO TEIXEIRA',
            'MUNICÍPIO DE PEQUERI',
            'MUNICÍPIO DE PEQUI',
            'MUNICÍPIO DE PERDIGÃO',
            'MUNICÍPIO DE PERDIZES',
            'MUNICÍPIO DE PERDÕES',
            'INSTITUTO DE PREVIDENCIA MUNICIPAL DE PERDOES',
            'MUNICÍPIO DE PERIQUITO',
            'MUNICÍPIO DE PESCADOR',
            'MUNICÍPIO DE PIAU',
            'MUNICÍPIO DE PIEDADE DE CARATINGA',
            'MUNICÍPIO DE PIEDADE DE PONTE NOVA',
            'MUNICÍPIO DE PIEDADE DO RIO GRANDE',
            'MUNICÍPIO DE PIEDADE DOS GERAIS',
            "MUNICÍPIO DE PINGO-D'ÁGUA",
            'MUNICÍPIO DE PINTÓPOLIS',
            'MUNICÍPIO DE PIRACEMA',
            'INSTITUTO DE PREVIDENCIA MUN. DE PIRACEMA - PIRAPREV',
            'MUNICÍPIO DE PIRAJUBA',
            'MUNICÍPIO DE PIRANGUÇU',
            'MUNICÍPIO DE PIRANGUINHO',
            'MUNICÍPIO DE PIRAPETINGA',
            'FUNDAÇÃO MUNICIPAL DE SAÚDE',
            'MUNICÍPIO DE PIRAÚBA',
            'MUNICÍPIO DE PITANGUI',
            'INSTITUTO DE PREVIDENCIA MUNICIPAL DE PITANGUI',
            'MUNICÍPIO DE PIUMHI',
            'MUNICÍPIO DE POÇO FUNDO',
            'IMPREMPOF-INTITUTO DE PREVIDÊNCIA DO MUNICÍPIO DE POÇO FUNDO',
            'MUNICÍPIO DE POCRANE',
            'HOSPITAL MUNICIPAL JOSÉ VICTOR DE PAULA',
            'MUNICÍPIO DE POMPÉU',
            'MUNICÍPIO DE PONTE NOVA',
            'CÂMARA MUNICIPAL DE PONTE NOVA',
            'DMAES - DEPARTAMENTO MUNICIPAL DE ÁGUA ESGOTO E SANEAMENTO',
            'MUNICÍPIO DE PONTO DOS VOLANTES',
            'MUNICÍPIO DE PORTEIRINHA',
            'MUNICÍPIO DE PORTO FIRME',
            'MUNICÍPIO DE POUSO ALTO',
            'MUNICÍPIO DE PRADOS',
            'MUNICÍPIO DE PRATA',
            'MUNICÍPIO DE PRATÁPOLIS',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE PRATÁPOLIS',
            'MUNICÍPIO DE PRATINHA',
            'MUNICÍPIO DE PRESIDENTE BERNARDES',
            'MUNICÍPIO DE PRESIDENTE KUBITSCHEK',
            'MUNICÍPIO DE PRESIDENTE OLEGÁRIO',
            'MUNICÍPIO DE PRUDENTE DE MORAIS',
            'MUNICÍPIO DE QUARTEL GERAL',
            'MUNICÍPIO DE QUELUZITO',
            'MUNICÍPIO DE RAPOSOS',
            'MUNICÍPIO DE RAUL SOARES',
            'MUNICÍPIO DE RECREIO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE RECREIO',
            'MUNICÍPIO DE REDUTO',
            'MUNICÍPIO DE RESENDE COSTA',
            'MUNICÍPIO DE RESPLENDOR',
            'MUNICÍPIO DE RESSAQUINHA',
            'MUNICÍPIO DE RIACHINHO',
            'MUNICÍPIO DE RIBEIRÃO DAS NEVES',
            'MUNICÍPIO DE RIBEIRÃO VERMELHO',
            'MUNICÍPIO DE RIO ACIMA',
            'MUNICÍPIO DE RIO CASCA',
            'MUNICÍPIO DE RIO DO PRADO',
            'MUNICÍPIO DE RIO DOCE',
            'MUNICÍPIO DE RIO MANSO',
            'MUNICÍPIO DE RIO NOVO',
            'MUNICÍPIO DE RIO PARANAÍBA',
            'MUNICÍPIO DE RIO PIRACICABA',
            'MUNICÍPIO DE RIO POMBA',
            'MUNICÍPIO DE RIO PRETO',
            'MUNICÍPIO DE RIO VERMELHO',
            'MUNICÍPIO DE RITÁPOLIS',
            'MUNICÍPIO DE ROCHEDO DE MINAS',
            'MUNICÍPIO DE ROMARIA',
            'MUNICÍPIO DE ROSÁRIO DA LIMEIRA',
            'MUNICÍPIO DE RUBELITA',
            'MUNICÍPIO DE RUBIM',
            'MUNICÍPIO DE SABINÓPOLIS',
            'MUNICÍPIO DE SACRAMENTO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE SACRAMENTO',
            'MUNICÍPIO DE SALINAS',
            'MUNICÍPIO DE SALTO DA DIVISA',
            'MUNICÍPIO DE SANTA BÁRBARA',
            'MUNICÍPIO DE SANTA BÁRBARA DO MONTE VERDE',
            'MUNICÍPIO DE SANTA BÁRBARA DO TUGÚRIO',
            'MUNICÍPIO DE SANTA CRUZ DE MINAS',
            'MUNICÍPIO DE SANTA CRUZ DE SALINAS',
            'MUNICÍPIO DE SANTA CRUZ DO ESCALVADO',
            'MUNICÍPIO DE SANTA EFIGÊNIA DE MINAS',
            'MUNICÍPIO DE SANTA FÉ DE MINAS',
            'MUNICÍPIO DE SANTA HELENA DE MINAS',
            'MUNICÍPIO DE SANTA JULIANA',
            'MUNICÍPIO DE SANTA LUZIA',
            'IMPAS- INSTITUTO MUNIC. DE PREVIDÊNCIA SOCIAL DE SANTA LUZIA',
            'MUNICÍPIO DE SANTA MARIA DE ITABIRA',
            'MUNICÍPIO DE SANTA MARIA DO SALTO',
            'MUNICÍPIO DE SANTA RITA DE CALDAS',
            'MUNICÍPIO DE SANTA RITA DE MINAS',
            'MUNICÍPIO DE SANTA RITA DO IBITIPOCA',
            'MUNICÍPIO DE SANTA RITA DO ITUETO',
            'MUNICÍPIO DE SANTA ROSA DA SERRA',
            'MUNICÍPIO DE SANTA VITÓRIA',
            'MUNICÍPIO DE SANTANA DA VARGEM',
            'MUNICÍPIO DE SANTANA DE CATAGUASES',
            'MUNICÍPIO DE SANTANA DE PIRAPAMA',
            'MUNICÍPIO DE SANTANA DO DESERTO',
            'MUNICÍPIO DE SANTANA DO JACARÉ',
            'MUNICÍPIO DE SANTANA DO MANHUAÇU',
            'MUNICÍPIO DE SANTANA DO RIACHO',
            'MUNICÍPIO DE SANTANA DOS MONTES',
            'MUNICÍPIO DE SANTO ANTÔNIO DO AMPARO',
            'MUNICÍPIO DE SANTO ANTÔNIO DO AVENTUREIRO',
            'MUNICÍPIO DE SANTO ANTÔNIO DO GRAMA',
            'MUNICÍPIO DE SANTO ANTÔNIO DO ITAMBÉ',
            'MUNICÍPIO DE SANTO ANTÔNIO DO JACINTO',
            'MUNICÍPIO DE SANTO ANTÔNIO DO MONTE',
            'MUNICÍPIO DE SANTO ANTÔNIO DO RETIRO',
            'MUNICÍPIO DE SANTO HIPÓLITO',
            'MUNICÍPIO DE SÃO BENTO ABADE',
            'MUNICÍPIO DE SÃO BRÁS DO SUAÇUÍ',
            'MUNICÍPIO DE SÃO DOMINGOS DAS DORES',
            'MUNICÍPIO DE SÃO DOMINGOS DO PRATA',
            'MUNICÍPIO DE SÃO FÉLIX DE MINAS',
            'MUNICÍPIO DE SÃO FRANCISCO',
            'INSTITUTO DE PREV.DOS SERV.PÚB. MUN. DE SÃO FRANCISCO',
            'MUNICÍPIO DE SÃO FRANCISCO DE PAULA',
            'MUNICÍPIO DE SÃO FRANCISCO DO GLÓRIA',
            'MUNICÍPIO DE SÃO GERALDO',
            'MUNICÍPIO DE SÃO GERALDO DA PIEDADE',
            'MUNICÍPIO DE SÃO GONÇALO DO PARÁ',
            'MUNICÍPIO DE SÃO GONÇALO DO RIO ABAIXO',
            'MUNICÍPIO DE SÃO GONÇALO DO SAPUCAÍ',
            'MUNICÍPIO DE SÃO GOTARDO',
            'MUNICÍPIO DE SÃO JOÃO DA LAGOA',
            'MUNICÍPIO DE SÃO JOÃO DA MATA',
            'MUNICÍPIO DE SÃO JOÃO DAS MISSÕES',
            'MUNICÍPIO DE SÃO JOÃO DO MANHUAÇU',
            'MUNICÍPIO DE SÃO JOÃO DO MANTENINHA',
            'MUNICÍPIO DE SÃO JOÃO DO ORIENTE',
            'MUNICÍPIO DE SÃO JOÃO DO PACUÍ',
            'MUNICÍPIO DE SÃO JOÃO EVANGELISTA',
            'FUNDAÇÃO MUNICIPAL DE SAÚDE - PRÓ-SAÚDE',
            'MUNICÍPIO DE SÃO JOAQUIM DE BICAS',
            'MUNICÍPIO DE SÃO JOSÉ DA BARRA',
            'MUNICÍPIO DE SÃO JOSÉ DA LAPA',
            'MUNICÍPIO DE SÃO JOSÉ DA SAFIRA',
            'MUNICÍPIO DE SÃO JOSÉ DA VARGINHA',
            'MUNICÍPIO DE SÃO JOSÉ DO ALEGRE',
            'MUNICÍPIO DE SÃO JOSÉ DO DIVINO',
            'MUNICÍPIO DE SÃO JOSÉ DO GOIABAL',
            'MUNICÍPIO DE SÃO JOSÉ DO JACURI',
            'MUNICÍPIO DE SÃO JOSÉ DO MANTIMENTO',
            'MUNICÍPIO DE SÃO MIGUEL DO ANTA',
            'CONSORCIO INTERMUNICIPAL PARA GESTÃO DE RES.SOLIDOS URBANOS',
            'MUNICÍPIO DE SÃO PEDRO DA UNIÃO',
            'MUNICÍPIO DE SÃO PEDRO DO SUAÇUI',
            'MUNICÍPIO DE SÃO PEDRO DOS FERROS',
            'MUNICÍPIO DE SÃO ROMÃO',
            'MUNICÍPIO DE SÃO ROQUE DE MINAS',
            'MUNICÍPIO DE SÃO SEBASTIÃO DA BELA VISTA',
            'MUNICÍPIO DE SÃO SEBASTIÃO DA VARGEM ALEGRE',
            'MUNICÍPIO DE SÃO SEBASTIÃO DO ANTA',
            'MUNICÍPIO DE SÃO SEBASTIÃO DO OESTE',
            'IPSEM- INST. DE PREV. DOS SERV. M. DE SÃO SEBASTIÃO DO OESTE',
            'MUNICÍPIO DE SÃO SEBASTIÃO DO RIO PRETO',
            'MUNICÍPIO DE SÃO SEBASTIÃO DO RIO VERDE',
            'MUNICÍPIO DE SÃO TIAGO',
            'MUNICÍPIO DE SÃO TOMÁS DE AQUINO',
            'MUNICÍPIO DE SÃO TOMÉ DAS LETRAS',
            'MUNICÍPIO DE SÃO VICENTE DE MINAS',
            'MUNICÍPIO DE SAPUCAÍ-MIRIM',
            'MUNICÍPIO DE SARDOÁ',
            'MUNICÍPIO DE SARZEDO',
            'MUNICÍPIO DE SEM-PEIXE',
            'MUNICÍPIO DE SENADOR AMARAL',
            'MUNICÍPIO DE SENADOR CORTES',
            'MUNICÍPIO DE SENADOR FIRMINO',
            'MUNICÍPIO DE SENADOR JOSÉ BENTO',
            'MUNICÍPIO DE SENHORA DE OLIVEIRA',
            'MUNICÍPIO DE SENHORA DO PORTO',
            'MUNICÍPIO DE SENHORA DOS REMÉDIOS',
            'MUNICÍPIO DE SERICITA',
            'MUNICÍPIO DE SERITINGA',
            'MUNICÍPIO DE SERRA AZUL DE MINAS',
            'MUNICÍPIO DE SERRA DA SAUDADE',
            'MUNICÍPIO DE SERRA DOS AIMORÉS',
            'MUNICÍPIO DE SERRANIA',
            'MUNICÍPIO DE SERRO',
            'MUNICÍPIO DE SETUBINHA',
            'MUNICÍPIO DE SILVEIRÂNIA',
            'MUNICÍPIO DE SILVIANÓPOLIS',
            'MUNICÍPIO DE SOBRÁLIA',
            'MUNICÍPIO DE SOLEDADE DE MINAS',
            'MUNICÍPIO DE TABULEIRO',
            'MUNICÍPIO DE TAPIRA',
            'MUNICÍPIO DE TAPIRAÍ',
            'MUNICÍPIO DE TAQUARAÇU DE MINAS',
            'MUNICÍPIO DE TIRADENTES',
            'MUNICÍPIO DE TIROS',
            'MUNICÍPIO DE TOCANTINS',
            'FUNDO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS MUNICIPAIS',
            'MUNICÍPIO DE TOCOS DO MOJI',
            'MUNICÍPIO DE TOLEDO',
            'MUNICÍPIO DE TOMBOS',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE TOMBOS',
            'MUNICÍPIO DE TRÊS CORAÇÕES',
            'INST. DE PREV. MUN.DE TRÊS CORAÇÕES- IPRECOR',
            'MUNICÍPIO DE TRÊS MARIAS',
            'MUNICÍPIO DE TRÊS PONTAS',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE TRÊS PONTAS',
            'MUNICÍPIO DE TUMIRITINGA',
            'MUNICÍPIO DE TUPACIGUARA',
            'MUNICÍPIO DE TURMALINA',
            'MUNICÍPIO DE TURVOLÂNDIA',
            'MUNICÍPIO DE UBÁ',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS',
            'MUNICÍPIO DE UBAÍ',
            'MUNICÍPIO DE UBAPORANGA',
            'MUNICÍPIO DE UMBURATIBA',
            'MUNICÍPIO DE UNAÍ',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS MUNICIPAIS',
            'MUNICÍPIO DE URUANA DE MINAS',
            'MUNICÍPIO DE URUCÂNIA',
            'MUNICÍPIO DE URUCUIA',
            'MUNICÍPIO DE VARGEM ALEGRE',
            'MUNICÍPIO DE VARGEM BONITA',
            'MUNICÍPIO DE VARGEM GRANDE DO RIO PARDO',
            'MUNICÍPIO DE VARGINHA',
            'HOSPITAL REGIONAL DO SUL DE MINAS',
            'FHOMUV - FUNDAÇÃO HOSPITALAR DO MUNICIPIO DE VARGINHA',
            'FUNDAÇÃO CULTURAL DO MUNICIPIO DE VARGINHA',
            'INST. DE PREVIDENCIA DOS SERV.PUBLICOS DO M.VARGINHA-INPREV',
            'GUARDA CIVIL MUNICIPAL DE VARGINHA',
            'MUNICÍPIO DE VARJÃO DE MINAS',
            'MUNICÍPIO DE VÁRZEA DA PALMA',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES MUNICIPAIS',
            'FUNDAÇÃO MUNICIPAL DE SAÚDE',
            'MUNICÍPIO DE VARZELÂNDIA',
            'MUNICÍPIO DE VAZANTE',
            'MUNICÍPIO DE VERDELÂNDIA',
            'MUNICÍPIO DE VEREDINHA',
            'MUNICÍPIO DE VERÍSSIMO',
            'MUNICÍPIO DE VERMELHO NOVO',
            'MUNICÍPIO DE VESPASIANO',
            'MUNICÍPIO DE VIÇOSA',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE VIÇOSA',
            'INSTITUTO DE PREV. MUN. DOS SERV. PÚBLICOS DO MUN. DE VIÇOSA',
            'INST. MUN. DE ASSISTENCIA AOS SERVIDORES - IMAS',
            'MUNICÍPIO DE VIEIRAS',
            'MUNICÍPIO DE VIRGÍNIA',
            'MUNICÍPIO DE VIRGINÓPOLIS',
            'MUNICÍPIO DE VIRGOLÂNDIA',
            'MUNICÍPIO DE VISCONDE DO RIO BRANCO',
            'FUMPREV - FUNDO DE PREV. DO MUN. DE VISCONDE DO RIO BRANCO',
            'MUNICÍPIO DE VOLTA GRANDE',
            'MUNICÍPIO DE WENCESLAU BRAZ',
        ],
        ESPECIAL: [
            "ESTADO DE MINAS GERAIS",
            "MUNICÍPIO DE ABAETÉ",
            "MUNICÍPIO DE ABRE-CAMPO",
            "MUNICÍPIO DE ACAIACA",
            "MUNICÍPIO DE ÁGUA BOA",
            "MUNICÍPIO DE ÁGUAS VERMELHAS",
            "MUNICÍPIO DE AIURUOCA",
            "MUNICÍPIO DE ALFENAS",
            "MUNICÍPIO DE ALPERCATA",
            "MUNICÍPIO DE ALPINÓPOLIS",
            "MUNICÍPIO DE ARANTINA",
            "MUNICÍPIO DE ARAXÁ",
            "MUNICÍPIO DE ATALÉIA",
            "MUNICÍPIO DE BARROSO",
            "MUNICÍPIO DE BELO HORIZONTE",
            "MUNICÍPIO DE BELO ORIENTE",
            "MUNICÍPIO DE BERTÓPOLIS",
            "MUNICÍPIO DE BETIM",
            "MUNICÍPIO DE BOCAINA DE MINAS",
            "MUNICÍPIO DE BURITIZEIRO",
            "MUNICÍPIO DE CAETÉ",
            "MUNICÍPIO DE CAMPOS ALTOS",
            "MUNICÍPIO DE CANA VERDE",
            "MUNICÍPIO DE CANDEIAS",
            "MUNICÍPIO DE CAPELINHA",
            "MUNICÍPIO DE CAPIM BRANCO",
            "MUNICÍPIO DE CAPITÃO ANDRADE",
            "MUNICÍPIO DE CAPUTIRA",
            "MUNICÍPIO DE CARANGOLA",
            "MUNICÍPIO DE CARMO DA MATA",
            "MUNICÍPIO DE CATAGUASES",
            "MUNICÍPIO DE CENTRALINA",
            "MUNICÍPIO DE CONSELHEIRO LAFAIETE",
            "MUNICÍPIO DE CONSELHEIRO PENA",
            "MUNICÍPIO DE CONTAGEM",
            "MUNICÍPIO DE COROACI",
            "MUNICÍPIO DE CÓRREGO DO BOM JESUS",
            "MUNICÍPIO DE DELFINÓPOLIS",
            "MUNICÍPIO DE DIVINÓPOLIS",
            "MUNICÍPIO DE DIVISA ALEGRE",
            "MUNICÍPIO DE ENGENHEIRO NAVARRO",
            "MUNICÍPIO DE ESPINOSA",
            "MUNICÍPIO DE ESTIVA",
            "MUNICÍPIO DE ESTRELA DO SUL",
            "MUNICÍPIO DE GOUVEIA",
            "MUNICÍPIO DE GRUPIARA",
            "MUNICÍPIO DE GUARACIABA",
            "MUNICÍPIO DE GUARANÉSIA",
            "MUNICÍPIO DE GURINHATÃ",
            "MUNICÍPIO DE IBIÁ",
            "MUNICÍPIO DE IBIAÍ",
            "MUNICÍPIO DE IBIRITÉ",
            "MUNICÍPIO DE IGUATAMA",
            "MUNICÍPIO DE IPANEMA",
            "MUNICÍPIO DE IPATINGA",
            "MUNICÍPIO DE ITABIRA",
            "MUNICÍPIO DE ITAMONTE",
            "MUNICÍPIO DE ITUIUTABA",
            "MUNICÍPIO DE JANAÚBA",
            "MUNICÍPIO DE JEQUITAÍ",
            "MUNICÍPIO DE JOANÉSIA",
            "MUNICÍPIO DE JOÃO MONLEVADE",
            "MUNICÍPIO DE LAJINHA",
            "MUNICÍPIO DE LAVRAS",
            "MUNICÍPIO DE LEOPOLDINA",
            "MUNICÍPIO DE MANHUAÇU",
            "MUNICÍPIO DE MARAVILHAS",
            "MUNICÍPIO DE MATIAS BARBOSA",
            "MUNICÍPIO DE MEDINA",
            "MUNICÍPIO DE MESQUITA",
            "MUNICÍPIO DE MONTE AZUL",
            "MUNICÍPIO DE MONTE SIÃO",
            "MUNICÍPIO DE MONTES CLAROS",
            "MUNICÍPIO DE MURIAÉ",
            "MUNICÍPIO DE NANUQUE",
            "MUNICÍPIO DE NOVA LIMA",
            "MUNICÍPIO DE OURO VERDE DE MINAS",
            "MUNICÍPIO DE PADRE PARAÍSO",
            "MUNICÍPIO DE PALMÓPOLIS",
            "MUNICÍPIO DE PASSOS",
            "MUNICÍPIO DE PATROCÍNIO",
            "MUNICÍPIO DE PATROCÍNIO DO MURIAÉ",
            "MUNICÍPIO DE PEDRO LEOPOLDO",
            "MUNICÍPIO DE PIMENTA",
            "MUNICÍPIO DE PIRANGA",
            "MUNICÍPIO DE PIRAPORA",
            "MUNICÍPIO DE PLANURA",
            "MUNICÍPIO DE POÇOS DE CALDAS",
            "MUNICÍPIO DE POTÉ",
            "MUNICÍPIO DE POUSO ALEGRE",
            "MUNICÍPIO DE RIACHO DOS MACHADOS",
            "MUNICÍPIO DE RIO ESPERA",
            "MUNICÍPIO DE RIO PARDO DE MINAS",
            "MUNICÍPIO DE ROMARIA",
            "MUNICÍPIO DE SABARÁ",
            "MUNICÍPIO DE SANTA BÁRBARA DO LESTE",
            "MUNICÍPIO DE SANTA MARGARIDA",
            "MUNICÍPIO DE SANTA MARIA DO SUAÇUÍ",
            "MUNICÍPIO DE SANTA RITA DO JACUTINGA",
            "MUNICÍPIO DE SANTA RITA DO SAPUCAÍ",
            "MUNICÍPIO DE SANTANA DO PARAÍSO",
            "MUNICÍPIO DE SANTOS DUMONT",
            "MUNICÍPIO DE SÃO FRANCISCO DE SALES",
            "MUNICÍPIO DE SÃO GONÇALO DO ABAETÉ",
            "MUNICÍPIO DE SÃO JOÃO BATISTA DO GLÓRIA",
            "MUNICÍPIO DE SÃO JOÃO DA PONTE",
            "MUNICÍPIO DE SÃO JOÃO DEL-REI",
            "MUNICÍPIO DE SÃO JOÃO DO PARAÍSO",
            "MUNICÍPIO DE SÃO JOÃO NEPOMUCENO",
            "MUNICÍPIO DE SÃO LOURENÇO",
            "MUNICÍPIO DE SÃO SEBASTIÃO DO MARANHÃO",
            "MUNICÍPIO DE SÃO SEBASTIÃO DO PARAÍSO",
            "MUNICÍPIO DE SENADOR MODESTINO GONÇALVES",
            "MUNICÍPIO DE SETE LAGOAS",
            "MUNICÍPIO DE SIMONÉSIA",
            "MUNICÍPIO DE SOBRÁLIA",
            "MUNICÍPIO DE TAIOBEIRAS",
            "MUNICÍPIO DE TARUMIRIM",
            "MUNICÍPIO DE TEIXEIRAS",
            "MUNICÍPIO DE TEÓFILO OTÔNI",
            "MUNICÍPIO DE TIMÓTEO",
            "MUNICÍPIO DE UBERABA",
            "MUNICÍPIO DE UBERLÂNDIA",
            "MUNICÍPIO DE UNIÃO DE MINAS",
            "MUNICÍPIO DE VARGEM GRANDE DO RIO PARDO",
            "MUNICÍPIO DE VIRGEM DA LAPA",

        ]
    },
    PA: {
        COMUM: [
            "ESTADO DO PARÁ",
            "INSTITUTO DE GESTÃO PREVIDENCIÁRIA DO ESTADO DO PARA",
            "CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO PARA",
            "DEPARTAMENTO DE TRANSITO DO ESTADO DO PARA",
            "UNIVERSIDADE DO ESTADO DO PARÁ",
            "ABEL FIGUEIREDO",
            "ACARÁ",
            "ÁGUA AZUL DO NORTE",
            "ALENQUER",
            "ALMEIRIM",
            "ANAJÁS",
            "ANANINDEUA",
            "AVEIRO",
            "BAIÃO",
            "BELTERRA",
            "BRAGANÇA",
            "BREJO GRANDE DO ARAGUAIA",
            "BUJARU",
            "CANAÃ DOS CARAJÁS",
            "CHAVES",
            "CONCÓRDIA DO PARÁ",
            "CURIONÓPOLIS",
            "CURUÁ",
            "CURUÇÁ",
            "DOM ELISEU",
            "FARO",
            "GARRAFÃO DO NORTE",
            "GOIANÉSIA DO PARÁ",
            "GURUPÁ",
            "IGARAPÉ MIRI",
            "ITAITUBA",
            "JACUNDÁ",
            "JURUTI",
            "LIMOEIRO DO AJURU",
            "MARABÁ",
            "MARAPANIM",
            "MARITUBA",
            "MEDICILÂNDIA",
            "MELGAÇO",
            "MOCAJUBA",
            "MOJU",
            "MOJUÍ DOS CAMPOS",
            "MUANÁ",
            "NOVA ESPERANÇA DO PIRIÁ",
            "NOVA TIMBOTEUA",
            "ÓBIDOS",
            "PARAGOMINAS",
            "PARAUAPEBAS",
            "PAU D'ARCO",
            "PEIXE-BOI",
            "PONTA DE PEDRAS",
            "PORTEL",
            "PORTO DE MOZ",
            "PRAINHA",
            "REDENÇÃO",
            "RONDON DO PARÁ",
            "RURÓPOLIS",
            "SANTA IZABEL DO PARÁ",
            "SANTA LUZIA DO PARÁ",
            "SANTARÉM",
            "SANTO ANTÔNIO DO TAUÁ",
            "SÃO DOMINGOS DO CAPIM",
            "SÃO FRANCISCO DO PARÁ",
            "SÃO JOÃO DA PONTA",
            "SÃO JOÃO DE PIRABAS",
            "SÃO JOÃO DO ARAGUAIA",
            "SÃO MIGUEL DO GUAMÁ",
            "SÃO SEBASTIÃO DA BOA VISTA",
            "SOURE",
            "TAILÂNDIA",
            "TERRA SANTA",
            "TOMÉ-AÇU",
            "ULIANÓPOLIS",
            "VIGIA",
            "VISEU",
            "XINGUARA",
            "ITUPIRANGA"
        ],
        ESPECIAL: [
            "BELÉM",
            "AURORA DO PARÁ",
            "BOM JESUS DO TOCANTINS",
            "TUCURUÍ",

        ]
    },
    PB: {
        COMUM: [
            "AGUA BRANCA",
            "AGUIAR",
            "ALGODAO DE JANDAIRA",
            "ALHANDRA",
            "APARECIDA",
            "AREIA DE BARAÚNAS",
            "AREIAL",
            "ASSUNÇÃO",
            "BARRA DE SANTANA",
            "BELÉM DO BREJO DO CRUZ",
            "BERNARDINO BATISTA",
            "BOA VISTA",
            "BOM SUCESSO",
            "BORBOREMA",
            "BREJO DOS SANTOS",
            "CABACEIRAS",
            "CACHOEIRA DOS ÍNDIOS",
            "CAJAZEIRINHAS",
            "CALDAS BRANDÃO",
            "CAMALAÚ",
            "CARRAPATEIRA",
            "CASSERENGUE",
            "CATOLÉ DO ROCHA",
            "CATURITÉ",
            "CONDE",
            "CONGO",
            "COREMAS",
            "CRUZ DO ESPÍRITO SANTO",
            "CUITÉ DE MAMANGUAPE",
            "CURRAL DE CIMA",
            "CURRAL VELHO",
            "DAMIÃO",
            "DONA INÊS",
            "FREI MARTINHO",
            "GADO BRAVO",
            "GURJÃO",
            "IBIARA",
            "IMACULADA",
            "JERICÓ",
            "JOÃO PESSOA",
            "JOCA CLAUDINO",
            "JURIPIRANGA",
            "LAGOA",
            "LIVRAMENTO",
            "LUCENA",
            "MANAÍRA",
            "MATARACA",
            "MATINHAS",
            "MATO GROSSO",
            "MONTE HOREBE",
            "NATUBA",
            "NOVA PALMEIRA",
            "OLIVEDOS",
            "PASSAGEM",
            "PAULISTA",
            "PEDRA BRANCA",
            "PEDRA LAVRADA",
            "PEDRAS DE FOGO",
            "PEDRO RÉGIS",
            "PITIMBU",
            "POÇO DE JOSÉ MOURA",
            "POMBAL",
            "PRATA",
            "PUXINANÃ",
            "QUIXABA",
            "RIACHÃO",
            "RIACHÃO DO BACAMARTE",
            "RIACHO DE SANTO ANTONIO",
            "RIO TINTO",
            "SALGADINHO",
            "SALGADO DE SÃO FÉLIX",
            "SANTA CECÍLIA",
            "SANTA INÊS",
            "SANTA LUZIA",
            "SANTA RITA",
            "SANTANA DE MANGUEIRA",
            "SANTANA DOS GARROTES",
            "SANTO ANDRÉ",
            "SÃO BENTINHO",
            "SÃO BENTO",
            "SÃO DOMINGOS",
            "SÃO JOÃO DO CARIRI",
            "SÃO JOÃO DO TIGRE",
            "SÃO JOSÉ DA LAGOA TAPADA",
            "SÃO JOSÉ DE ESPINHARAS",
            "SÃO JOSÉ DO BONFIM",
            "SÃO JOSÉ DO BREJO DO CRUZ",
            "SÃO JOSÉ DO SABUGI",
            "SÃO JOSÉ DOS CORDEIROS",
            "SÃO MIGUEL DE TAIPU",
            "SÃO SEBASTIÃO DE LAGOA DE ROCA",
            "SERRA BRANCA",
            "SERRA GRANDE",
            "SERTÃOZINHO",
            "SOBRADO",
            "TEIXEIRA",
            "TENÓRIO",
            "VÁRZEA",
            "VIEIRÓPOLIS",
            "VISTA SERRANA",
        ],
        ESPECIAL: [
            "ALAGOA GRANDE",
            "ALAGOINHA",
            "ARAÇAGI",
            "ARARA",
            "ARARUNA",
            "AREIA",
            "AROEIRAS",
            "BANANEIRAS",
            "BARRA DE SANTA ROSA",
            "BARRA DE SÃO MIGUEL",
            "BAYEUX",
            "BELÉM",
            "BOA VENTURA",
            "BOM JESUS",
            "BONITO DE SANTA FÉ",
            "BOQUEIRÃO",
            "BREJO DO CRUZ",
            "CAAPORÃ",
            "CABEDELO",
            "CACIMBA DE AREIA",
            "CACIMBA DE DENTRO",
            "CAIÇARA",
            "CAJAZEIRAS",
            "CAMPINA GRANDE",
            "CATINGUEIRA",
            "CONCEIÇÃO",
            "CONDADO",
            "CUBATI",
            "CUITÉ",
            "CUITEGI",
            "DIAMANTE",
            "DUAS ESTRADAS",
            "EMAS",
            "ESPERANÇA",
            "FAGUNDES",
            "GUARABIRA",
            "GURINHÉM",
            "IGARACY",
            "INGÁ",
            "ITABAIANA",
            "ITAPORANGA",
            "ITAPOROROCA",
            "ITATUBA",
            "JACARAÚ",
            "JUAREZ TÁVORA",
            "JUAZEIRINHO",
            "JUNCO DO SERIDÓ",
            "JURU",
            "LAGOA DE DENTRO",
            "LAGOA SECA",
            "LASTRO",
            "MALTA",
            "MAMANGUAPE",
            "MARI",
            "MARIZÓPOLIS",
            "MASSARANDUBA",
            "MONTEIRO",
            "MULUNGU",
            "NAZAREZINHO",
            "NOVA FLORESTA",
            "NOVA OLINDA",
            "OLHO D'ÁGUA",
            "OURO VELHO",
            "PATOS",
            "PIANCÓ",
            "PILAR",
            "PILÕES",
            "PILÕEZINHOS",
            "PIRPIRITUBA",
            "POCINHOS",
            "PRINCESA ISABEL",
            "QUEIMADAS",
            "REMÍGIO",
            "RIACHO DOS CAVALOS",
            "SANTA CRUZ",
            "SANTA HELENA",
            "SANTA TEREZINHA",
            "SÃO JOÃO DO RIO DO PEIXE",
            "SÃO JOSÉ DE CAIANA",
            "SÃO JOSÉ DE PIRANHAS",
            "SÃO MAMEDE",
            "SÃO SEBASTIÃO DO UMBUZEIRO",
            "SÃO VICENTE DO SERIDÓ",
            "SAPÉ",
            "SERRA DA RAIZ",
            "SERRA REDONDA",
            "SERRARIA",
            "SOLÂNEA",
            "SOLEDADE",
            "SOSSEGO",
            "SOUSA",
            "SUMÉ",
            "TACIMA",
            "TAPEROÁ",
            "TAVARES",
            "TRIUNFO",
            "UIRAÚNA",
            "UMBUZEIRO",
            "ESTADO DA PARAÍBA",
        ]
    },
    PR: {
        COMUM: [
            "ADRIANÓPOLIS",
            "ÁGUAS DE SARANDI - SERVIÇO MUNICIPAL DE SANEAMENTO AMBIENTAL",
            "AGUDOS DO SUL",
            "ALTAMIRA DO PARANÁ",
            "ALTÔNIA",
            "ALTO PARAÍSO",
            "ALTO PARANÁ",
            "ALVORADA DO SUL",
            "AMAPORÃ",
            "AMPÉRE",
            "ANAHY",
            "ÂNGULO",
            "ARAPIRACA (AL)",
            "ARAPONGAS",
            "ARAPOTI",
            "ARARUNA",
            "ARAUCÁRIA",
            "ARIRANHA DO IVAÍ",
            "ASSAÍ",
            "ASSIS CHATEAUBRIAND",
            "ASTORGA",
            "ATALAIA",
            "AUTARQUIA MUNICIPAL DE PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE CAMBÉ - CAMBÉ PREVIDÊNCIA",
            "BALSA NOVA",
            "BARBOSA FERRAZ",
            "BARRACÃO",
            "BELA VISTA DA CAROBA",
            "BELA VISTA DO PARAÍSO",
            "BOA ESPERANÇA",
            "BOCAIÚVA DO SUL",
            "BOM SUCESSO DO SUL",
            "BRAGANEY",
            "CAFELÂNDIA",
            "CAFEZAL DO SUL",
            "CAIXA DE APOSENTADORIA E PENSÃO DOS SERVIDORES MUNICIPAIS DE IRATI - CAPSIRATI",
            "CAIXA DE PREVIDÊNCIA E ASSISTÊNCIA SOCIAL DO MUNICÍPIO DE INAJÁ",
            "CAIXA DE PREVIDÊNCIA E PENSÕES DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE CIANORTE - CAPSECI",
            "CÂMARA MUNICIPAL DE MARINGÁ",
            "CAMBÉ",
            "CAMPINA DA LAGOA",
            "CAMPINA DO SIMÃO",
            "CAMPINA GRANDE DO SUL",
            "CAMPO DO TENENTE",
            "CAMPO LARGO",
            "CAMPO MAGRO",
            "CAMPO MOURÃO",
            "CANDÓI",
            "CAPANEMA",
            "CAPITÃO LEÔNIDAS MARQUES",
            "CARAMBEÍ",
            "CARLÓPOLIS",
            "CASCAVEL",
            "CATANDUVAS",
            "CERRO AZUL",
            "CÉU AZUL",
            "CHOPINZINHO",
            "CIANORTE",
            "COLOMBO",
            "COLOMBO PREVIDÊNCIA - PREVIDÊNCIA DOS SERVIDORES PÚBLICOS MUNICIPAIS DE COLOMBO",
            "CONSELHEIRO MAIRINCK",
            "CONSÓRCIO INTERMUNICIPAL DE SAÚDE DO LITORAL DO PARANÁ - CISLIPA",
            "CONSÓRCIO INTERMUNICIPAL DE SAÚDE DO MÉDIO PARANAPANEMA - CISMEPAR",
            "CONSÓRCIO INTERMUNICIPAL DE SAÚDE DO NORTE DO PARANÁ - CISNOP",
            "CONTENDA",
            "CORBÉLIA",
            "CORNÉLIO PROCÓPIO",
            "CORONEL DOMINGOS SOARES",
            "CORUMBATAÍ DO SUL",
            "CRUZ MACHADO",
            "CRUZMALTINA",
            "CURITIBA",
            "DIAMANTE D'OESTE",
            "DIAMANTE DO NORTE",
            "DOIS VIZINHOS",
            "DOURADINA",
            "ENÉAS MARQUES",
            "ESPIGÃO ALTO DO IGUAÇU",
            "ESTRELA DO NORTE (SP)",
            "FAROL",
            "FAXINAL",
            "FAZENDA RIO GRANDE",
            "FLORAÍ",
            "FLOR DA SERRA DO SUL",
            "FLORESTA",
            "FORMOSA DO OESTE",
            "FOZ DO JORDÃO",
            "FRANCISCO ALVES",
            "FRANCISCO BELTRÃO",
            "FUNDAÇÃO CULTURAL DE CURITIBA",
            "FUNDAÇÃO DE AÇÃO SOCIAL DE CURITIBA - FAS",
            "FUNDAÇÃO HOSPITALAR DE SAÚDE MUNICIPAL DE IBAITI",
            "FUNDAÇÃO HOSPITALAR DR. JOSÉ ATHANAZIO (SC)",
            "FUNDO DE PREVIDÊNCIA DE NOVA AURORA - PREVINOVA",
            "FUNDO DE PREVIDENCIA MUNICIPAL DE ARAUCARIA",
            "FUNDO DE PREVIDÊNCIA MUNICIPAL DE PINHÃO - FUNPREV",
            "FUNDO MUNICIPAL DE SAÚDE - CANDÓI",
            "FUNDO MUNICIPAL DE SAÚDE DE QUEDAS DO IGUAÇU",
            "FUNDO PREVIDENCIÁRIO DO MUNICÍPIO DE TELÊMACO BORBA - FUNPREV",
            "FUNDO PREVIDENCIÁRIO MUNICIPAL DE TEIXEIRA SOARES",
            "FUNDO PREVIDENCIÁRIO MUNICIPAL DE UNIFLOR",
            "GENERAL CARNEIRO",
            "GODOY MOREIRA",
            "GOIOXIM",
            "GUAÍRA",
            "GUAIRAÇÁ",
            "GUAMIRANGA",
            "GUAPIRAMA",
            "GUAPOREMA",
            "GUARANIAÇU",
            "GUARAQUECABA",
            "IBAITI",
            "ICARAÍMA",
            "IGUARAÇU",
            "IGUATU",
            "IMBAÚ",
            "IMBITUVA",
            "INÁCIO MARTINS",
            "INAJÁ",
            "INSTITUTO DE PESQUISA E PLANEJAMENTO URBANO DE CURITIBA - IPPUC",
            "INSTITUTO DE PREVIDÊNCIA DE PRUDENTÓPOLIS",
            "INSTITUTO DE PREVIDÊNCIA DO MUNICÍPIO DE CRUZEIRO DO SUL",
            "INSTITUTO DE PREVIDÊNCIA DO MUNICÍPIO DE TAPEJARA",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO MUNICÍPIO DE CURITIBA- IPMC",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES MUNICIPAIS DE ARAPOTI - IPSM",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE CASCAVEL - IPMC",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE NOVA ESPERANÇA",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE RESERVA - RESERVA PREV",
            "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DO MUNICÍPIO DE QUERÊNCIA DO NORTE - INPAM",
            "IPIRANGA",
            "IPORÃ",
            "IRATI",
            "ITAGUAJÉ",
            "ITAIPULÂNDIA",
            "ITAMBARACÁ",
            "ITAMBÉ",
            "ITAPEJARA D´OESTE",
            "ITAPERUÇU",
            "ITAÚNA DO SUL",
            "IVAÍ",
            "IVAIPORÃ",
            "IVATÉ",
            "JABOTI",
            "JAGUAPITÃ",
            "JANDAIA DO SUL",
            "JANIÓPOLIS",
            "JARDIM ALEGRE",
            "JOAQUIM TÁVORA",
            "JUNDIAÍ DO SUL",
            "JURANDA",
            "JUSSARA",
            "LAPA",
            "LARANJAL",
            "LIDIANÓPOLIS",
            "LINDOESTE",
            "LOANDA",
            "LUIZIANA",
            "LUPIONÓPOLIS",
            "MANOEL RIBAS",
            "MARIA HELENA",
            "MARILÂNDIA DO SUL",
            "MARILENA",
            "MARILUZ",
            "MARINGÁ",
            "MARINGA PREVIDENCIA PREVIDENCIA DOS SERVIDORES PUBLICOS MUNICIPAIS DE MARINGA",
            "MARIPÁ",
            "MARQUINHO",
            "MARUMBI",
            "MEDIANEIRA",
            "MIRADOR",
            "MISSAL",
            "NOSSA SENHORA DAS GRAÇAS",
            "NOVA AURORA",
            "NOVA ESPERANÇA",
            "NOVA FÁTIMA",
            "NOVA LARANJEIRAS",
            "NOVA LONDRINA",
            "NOVA OLÍMPIA",
            "NOVA PRATA DO IGUAÇU",
            "NOVA SANTA ROSA",
            "NOVO ITACOLOMI",
            "ORTIGUEIRA",
            "OURIZONA",
            "OURO VERDE DO OESTE",
            "PAIÇANDU",
            "PALMAS",
            "PALMEIRA",
            "PALMITAL",
            "PALOTINA",
            "PANAMBI (RS)",
            "PARAÍSO DO NORTE",
            "PARANACITY",
            "PARANAVAÍ",
            "PARANAVAÍ PREVIDÊNCIA",
            "PAULA FREITAS",
            "PEABIRU",
            "PÉROLA",
            "PINHAIS",
            "PINHALÃO",
            "PINHAL DE SÃO BENTO",
            "PINHÃO",
            "PIRAÍ DO SUL",
            "PITANGA",
            "PITANGUEIRAS",
            "PLANALTINA DO PARANÁ",
            "PONTAL DO PARANÁ",
            "PORTO VITÓRIA",
            "PRADO FERREIRA",
            "PRANCHITA",
            "PRESIDENTE CASTELO BRANCO",
            "PREVIDÊNCIA SOCIAL DO MUNICÍPIO DE CAMPINA GRANDE DO SUL - PREVICAMP",
            "PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE CAMPO MOURÃO - PREVISCAM",
            "PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE FRANCISCO BELTRÃO - PREVBEL",
            "PREV SÃO JOSÉ - AUTARQUIA DE PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE SÃO JOSÉ DOS PINHAIS",
            "PRUDENTÓPOLIS",
            "QUARTO CENTENÁRIO",
            "QUATIGUÁ",
            "QUATRO BARRAS",
            "QUATRO PONTES",
            "QUEDAS DO IGUAÇU",
            "QUERÊNCIA DO NORTE",
            "QUINTA DO SOL",
            "QUITANDINHA",
            "RAMILÂNDIA",
            "RANCHO ALEGRE D'OESTE",
            "REALEZA",
            "REBOUÇAS",
            "RESERVA",
            "RESERVA DO IGUAÇU",
            "RIBEIRÃO CLARO",
            "RIBEIRÃO DO PINHAL",
            "RIO AZUL",
            "RIO BRANCO DO IVAÍ",
            "RIO NEGRO",
            "ROLÂNDIA",
            "RONDON",
            "SABÁUDIA",
            "SALTO DO LONTRA",
            "SANTA CECÍLIA DO PAVÃO",
            "SANTA FÉ",
            "SANTA HELENA",
            "SANTA ISABEL DO IVAÍ",
            "SANTA IZABEL DO OESTE",
            "SANTA MARIA DO OESTE",
            "SANTA MARIANA",
            "SANTA MÔNICA",
            "SANTA TEREZINHA DE ITAIPU",
            "SANTO ANTÔNIO DA PLATINA",
            "SANTO ANTÔNIO DO PARAÍSO",
            "SANTO ANTÔNIO DO SUDOESTE",
            "SANTO INÁCIO",
            "SÃO JOÃO DO CAIUÁ",
            "SÃO JOÃO DO TRIUNFO",
            "SÃO JORGE DO IVAÍ",
            "SÃO JOSÉ DOS PINHAIS",
            "SÃO MATEUS DO SUL",
            "SÃO MIGUEL DO IGUAÇU",
            "SÃO PEDRO DO IGUAÇU",
            "SÃO SEBASTIÃO DA AMOREIRA",
            "SAPOPEMA",
            "SARANDI",
            "SAUDADE DO IGUAÇU",
            "SENGÉS",
            "SERTANEJA",
            "SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE RIBEIRÃO CLARO",
            "SIQUEIRA CAMPOS",
            "SONORA (MS)",
            "SULINA",
            "TAPEJARA",
            "TELÊMACO BORBA",
            "TERRA RICA",
            "TERRA ROXA",
            "TIBAGI",
            "TRÊS BARRAS DO PARANÁ",
            "TUNAS DO PARANÁ",
            "TURVO",
            "UBIRATÃ",
            "UNIÃO DOS MUNICÍPIOS DA MÉDIA SOROCABANA - UMMES (SP)",
            "UNIFLOR",
            "UNIVERSIDADE ESTADUAL DO TOCANTINS - UNITINS (TO)",
            "VERÊ",
            "VIRMOND",
        ],
        ESPECIAL: [
            "ABATIÁ",
            "ADMINISTRAÇÃO DE CEMITÉRIOS E SERVIÇOS FUNERÁRIOS - ACESF UMUARAMA",
            "ADMINISTRAÇÃO DOS CEMITÉRIOS E SERVIÇOS FUNERÁRIOS DE LONDRINA - ACESF",
            "ADMINISTRAÇÃO DOS PORTOS DE PARANAGUÁ E ANTONINA - APPA",
            "ALMIRANTE TAMANDARÉ",
            "ANDIRÁ",
            "ANTONINA",
            "APARECIDA DE GOIÂNIA (GO)",
            "APUCARANA",
            "AUTARQUIA DOS SERVIÇOS FUNERÁRIOS DE APUCARANA - ASERFA",
            "AUTARQUIA MUNICIPAL DA EDUCAÇÃO DE APUCARANA",
            "AUTARQUIA MUNICIPAL DE EDUCAÇÃO DE CAMBIRA",
            "AUTARQUIA MUNICIPAL DE SAÚDE DE APUCARANA",
            "AUTARQUIA MUNICIPAL DE SAÚDE DE CAMBIRA- AMS",
            "AUTARQUIA MUNICIPAL DE SAÚDE DE LONDRINA",
            "AUTARQUIA MUNICIPAL DE TRÂNSITO E TRANSPORTE DE PONTA GROSSA",
            "BANDEIRANTES",
            "BARRA DO JACARÉ",
            "BITURUNA",
            "BOA VISTA DA APARECIDA",
            "BOM SUCESSO",
            "BORRAZÓPOLIS",
            "CAIXA DE ASSISTÊNCIA, APOSENTADORIA E PENSÕES DOS SERVIDORES MUNICIPAIS DE LONDRINA - CAAPSML",
            "CAIXA DE ASSISTÊNCIA DOS SERVIDORES MUNICIPAIS DE TOLEDO - CAST",
            "CAMBARÁ",
            "CAMBIRA",
            "CANTAGALO",
            "CASTRO",
            "CENTENÁRIO DO SUL",
            "CENTRO CULTURAL TEATRO GUAÍRA",
            "CIDADE GAÚCHA",
            "CLEVELÂNDIA",
            "COLORADO",
            "CONGONHINHAS",
            "COORDENAÇÃO DA REGIÃO METROPOLITANA DE CURTIBA - COMEC",
            "CORONEL VIVIDA",
            "CRUZEIRO DO OESTE",
            "CURIÚVA",
            "DEPARTAMENTO DE ESTRADAS DE RODAGEM DE SÃO PAULO - DER (SP)",
            "DEPARTAMENTO DE ESTRADAS DE RODAGEM DO PARANÁ - DER/PR",
            "DEPARTAMENTO DE TRÂNSITO DO ESTADO DO PARANÁ - DETRAN/PR",
            "DEPARTAMENTO ESTADUAL DE INFRAESTRUTURA - DEINFRA (SC)",
            "DEPARTAMENTO ESTADUAL DE TRÂNSITO DA BAHIA - DETRAN (BA)",
            "DEPARTAMENTO ESTADUAL DE TRÂNSITO DE SÃO PAULO - DETRAN (SP)",
            "DOUTOR ULYSSES",
            "ENGENHEIRO BELTRÃO",
            "ESCOLA DE MÚSICA E BELAS ARTES DO PARANÁ - EMBAP",
            "ESTADO DA BAHIA (BA)",
            "ESTADO DE MINAS GERAIS (MG)",
            "ESTADO DE RONDÔNIA (RO)",
            "ESTADO DE SANTA CATARINA (SC)",
            "ESTADO DE SÃO PAULO (SP)",
            "ESTADO DO CEARÁ (CE)",
            "ESTADO DO MATO GROSSO DO SUL (MS)",
            "ESTADO DO PARANÁ",
            "ESTADO DO RIO DE JANEIRO (RJ)",
            "ESTADO DO TOCANTINS (TO)",
            "FACULDADE ESTADUAL DE EDUCAÇÃO, CIÊNCIAS E LETRAS DE PARANAVAÍ",
            "FACULDADE ESTADUAL DE FILOSOFIA, CIÊNCIAS E LETRAS DE CORNÉLIO PROCÓPIO - UENP/FAFICOP",
            "FÊNIX",
            "FIGUEIRA",
            "FLORESTÓPOLIS",
            "FLORIANÓPOLIS (SC)",
            "FOZ DO IGUAÇU",
            "FOZ PREVIDÊNCIA - FOZPREV",
            "FUNDAÇÃO DE SAÚDE PÚBLICA DE NOVO HAMBURGO - FSNH (RS)",
            "FUNDAÇÃO FACULDADE ESTADUAL DE FILOSOFIA, CIÊNCIA E LETRAS DE JACAREZINHO",
            "FUNDAÇÃO MUNICIPAL DE SAÚDE DE BITURUNA - FUSA",
            "FUNDAÇÃO MUNICIPAL DE SAÚDE DE FOZ DO IGUAÇU",
            "FUNDAÇÃO MUNICIPAL DE SAÚDE DE UNIÃO DA VITÓRIA - FUSA",
            "FUNDAÇÃO MUNICIPAL DE TURISMO DE PARANAGUÁ - FUMTUR",
            "FUNDO DE PREVIDÊNCIA DOS SERVIDORES MUNICIPAIS DE MANDIRITUBA",
            "FUNDO DE PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE ANDIRÁ - FUNPESPA",
            "FUNDO MUNICIPAL DE DESENVOLVIMENTO DE MARECHAL CÂNDIDO RONDON",
            "FUNDO PARA CUSTEIO PREVIDENCIÁRIO DA APOSENTADORIA E PENSÕES DOS FUNCIONÁRIOS DA ADMINISTRAÇÃO PÚBLICA DIRETA E ","INDIRETA DO MUNICÍPIO DE UNIÃO DA VITÓRIA - FUMPREVI",
            "GOIOERÊ",
            "GOVERNO DO PARANÁ - SECRETARIA DE ESTADO DA FAZENDA",
            "GRANDES RIOS",
            "GUARAPREV",
            "GUARAPUAVA",
            "GUARATUBA",
            "HOSPITAL UNIVERSITÁRIO DO OESTE DO PARANÁ",
            "IACRI (SP)",
            "IBIPORÃ",
            "IBITINGA (SP)",
            "INSTITUTO ÁGUA E TERRA - IAT",
            "INSTITUTO DAS ÁGUAS DO PARANÁ",
            "INSTITUTO DE AÇÃO SOCIAL DO PARANÁ - IASP",
            "INSTITUTO DE DESENVOLVIMENTO DE LONDRINA - CODEL",
            "INSTITUTO DE DESENVOLVIMENTO RURAL DO PARANÁ - IAPAR - EMATER",
            "INSTITUTO DE PESOS E MEDIDAS DO ESTADO DO PARANÁ - IPEM",
            "INSTITUTO DE PREVIDÊNCIA DE IBIPORÃ",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES MILITARES DO ESTADO DE MINAS GERAIS (MG)",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE BOM SUCESSO-PR",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE CANTAGALO - IPSM DE CANTAGALO",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE COLORADO - COLORADO PREV",
            "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE GUARAPUAVA - GUARAPUAVA PREV",
            "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA AOS SERVIDORES DO ESTADO DO PARANÁ - IPE",
            "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA AOS SERVIDORES PÚBLICOS MUNICIPAIS DE JAGUARIAÍVA - IPASPMJ",
            "INSTITUTO DE SAÚDE DO PARANÁ - ISEP",
            "INSTITUTO DE TRANSPORTES E TRÂNSITO DE FOZ DO IGUAÇU - FOZTRANS",
            "INSTITUTO MUNICIPAL DE PREVIDÊNCIA DE CONGONHINHAS IMPC",
            "INSTITUTO PARANAENSE DE ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL - EMATER",
            "INSTITUTO PARANAENSE DE CIÊNCIA DO ESPORTE",
            "IRETAMA",
            "JACAREZINHO",
            "JAGUARIAÍVA",
            "JAPIRA",
            "JAPURÁ",
            "JATAIZINHO",
            "JUNTA COMERCIAL DO PARANÁ - JUCEPAR",
            "KALORÉ",
            "LARANJEIRAS DO SUL",
            "LEÓPOLIS",
            "LONDRINA",
            "LUNARDELLI",
            "MALLET",
            "MANDAGUARI",
            "MANDIRITUBA",
            "MANGUEIRINHA",
            "MARECHAL CÂNDIDO RONDON",
            "MARIALVA",
            "MATELÂNDIA",
            "MATINHOS",
            "MOREIRA SALES",
            "MORRETES",
            "NOVA AMÉRICA DA COLINA",
            "NOVA CANTU",
            "NOVA TEBAS",
            "PARANÁ EDIFICAÇÕES",
            "PARANAGUÁ",
            "PARANÁPREVIDÊNCIA",
            "PATO BRANCO",
            "PAULO FRONTIN",
            "PIRAQUARA",
            "PONTA GROSSA",
            "PORECATU",
            "POSSE (GO)",
            "PRIMEIRO DE MAIO",
            "PROCURADORIA GERAL DO ESTADO DE SÃO PAULO (SP)",
            "PROCURADORIA GERAL DO ESTADO DO PARANÁ",
            "RÁDIO E TELEVISÃO EDUCATIVA DO PARANÁ - TVE",
            "RANCHO ALEGRE",
            "RIO BONITO DO IGUAÇU",
            "RIO BRANCO DO SUL",
            "RONCADOR",
            "ROSANA (SP)",
            "ROSÁRIO DO IVAÍ",
            "SALGADO FILHO",
            "SALTO DO ITARARÉ",
            "SANTA AMÉLIA",
            "SANTA CRUZ DE MONTE CASTELO",
            "SANTA INÊS",
            "SANTANA DO ITARARÉ",
            "SANTA TEREZA DO OESTE",
            "SÃO JERÔNIMO DA SERRA",
            "SÃO JOÃO DO IVAÍ",
            "SÃO JORGE D'OESTE",
            "SÃO PEDRO DO IVAÍ",
            "SÃO TOMÉ",
            "SERTANÓPOLIS",
            "SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE BANDEIRANTES",
            "SERVIÇO AUTÔNOMO DE PAVIMENTAÇÃO DE UMUARAMA - SERAUPA",
            "SERVIÇO AUTÔNOMO MUNICIPAL DE ÁGUA E ESGOTO DE ANTONINA",
            "SERVIÇO AUTÔNOMO MUNICIPAL DE ÁGUA E ESGOTO DE IBIPORÃ",
            "SERVIÇO AUTÔNOMO MUNICIPAL DE ÁGUA E ESGOTO DE JAGUARIAÍVA",
            "SERVIÇO DE ÁGUA E ESGOTO DE MARIALVA  SAEMA",
            "SERVIÇO MUNICIPAL DE SAÚDE DE SERTANÓPOLIS",
            "SUPERINTENDÊNCIA DE DESENVOLVIMENTO DE RECURSOS HÍDRICOS E SANEAMENTO AMBIENTAL - SUDERHSA",
            "TAMBOARA",
            "TIJUCAS DO SUL",
            "TOLEDO",
            "TUNEIRAS DO OESTE",
            "UMUARAMA",
            "UNIÃO DA VITÓRIA",
            "UNIVERSIDADE ESTADUAL DE LONDRINA - UEL",
            "UNIVERSIDADE ESTADUAL DE MARINGÁ - UEM",
            "UNIVERSIDADE ESTADUAL DE PONTA GROSSA - UEPG",
            "UNIVERSIDADE ESTADUAL DO CENTRO OESTE - UNICENTRO",
            "UNIVERSIDADE ESTADUAL DO NORTE DO PARANÁ - CAMPUS CORNÉLIO PROCÓPIO",
            "UNIVERSIDADE ESTADUAL DO NORTE DO PARANÁ - CAMPUS JACAREZINHO",
            "UNIVERSIDADE ESTADUAL DO OESTE DO PARANÁ - CAMPUS CASCAVEL",
            "UNIVERSIDADE ESTADUAL DO OESTE DO PARANÁ - UNIOESTE",
            "UNIVERSIDADE ESTADUAL DO PARANÁ - UNESPAR",
            "UNIVERSIDADE ESTADUAL DO PARANÁ - UNESPAR - CAMPUS CAMPO MOURÃO",
            "URAÍ",
            "VERA CRUZ DO OESTE",
            "WENCESLAU BRAZ",
            "XAMBRÊ",
        ]
    },
    PE: {
        COMUM: [
            "AEB - Autarquia Educacional do Município do Belo Jardim",
            "AEDA - Autarquia Educacional do Araripe",
            "AEDS Autarquia Educacional de Salgueiro",
            "AESET Autarquia Educacional de Serra Talhada",
            "AESGA - Autarquia do Ensino Superior de Garanhuns",
            "ALTINHOPREV Autarquia Municipal de Previdência Social de Altinho",
            "Câmara Municipal de Barreiros",
            "CARUARUPREV Instituto de Previdência Social Municipal de Caruaru",
            "CTTU Autarquia de Transito e Transportes Urbanos do Recife",
            "EMLURB - Empresa Manutenção Limpeza Urbana Recife",
            "EMTT Empresa Municipal de Trânsito e Transportes de Jaboatão dos Guararapes",
            "Fundação de Cultura e Turismo de Caruaru",
            "FUNPREI - Fundo Previdenciário do Município do Ipojuca",
            "INSS - Instituto Nacional do Seguro Social",
            "IPSESE Instituto Previdência Servidores Municipais de Sertânia",
            "IPSC Instituto de Previdência dos Servidores de Caetés",
            "IPSG Instituto de Previdência dos Servidores Públicos do Município de Garanhuns",
            "IPSMAI Instituto Previdência dos Servidores do Município de Afogados Ingazeira",
            "Instituto de Previdência dos Servidores Municipais de Panelas",
            "JABOATÃOPREV Instituto de Previdência dos Servidores de Jaboatão dos Guararapes",
            "Município de Abreu e Lima",
            "Município de Afogados da Ingazeira",
            "Município de Afrânio",
            "Município de Agrestina",
            "Município de Aguas Belas",
            "Município de Agua Preta",
            "Município de Alagoinha",
            "Município de Aliança",
            "Município de Altinho",
            "Município de Amaraji",
            "Município de Angelim",
            "Município de Araçoiaba",
            "Município de Araripina",
            "Município de Arcoverde",
            "Município de Barreiros",
            "Município de Belém de Maria",
            "Município de Belém de São Francisco",
            "Município de Belo Jardim",
            "Município de Betânia",
            "Município de Bezerros",
            "Município de Bodocó",
            "Município de Bom Conselho",
            "Município de Bom Jardim",
            "Município de Bonito",
            "Município de Brejão",
            "Município de Brejinho",
            "Município de Brejo da Madre de Deus",
            "Município de Buíque",
            "Município de Cabo de Santo Agostinho",
            "Município de Cabrobó",
            "Município de Caetés",
            "Município de Calçado",
            "Município de Calumbi",
            "Município de Camaragibe",
            "Município de Camocim de São Félix",
            "Município de Canhotinho",
            "Município de Capoeiras",
            "Município de Carnaíba",
            "Município de Caruaru",
            "Município de Casinhas",
            "Município de Catende",
            "Município de Chã de Alegria",
            "Município de Chã Grande",
            "Município de Condado",
            "Município de Correntes",
            "Município de Cortês",
            "Município de Cumaru",
            "Município de Cupira",
            "Município de Escada",
            "Município de Exu",
            "Município de Feira Nova",
            "Município de Ferreiros",
            "Município de Flores",
            "Município de Frei Miguelinho",
            "Município de Gameleira",
            "Município de Garanhuns",
            "Município de Glória do Goitá",
            "Município de Gravatá",
            "Município de Ibimirim",
            "Município de Ibirajuba",
            "Município de Inajá",
            "Município de Ingazeira",
            "Município de Ipojuca",
            "Município de Ipubi",
            "Município de Itacuruba",
            "Município de Itaíba",
            "Município de Itamaracá",
            "Município de Itambé",
            "Município de Itapetim",
            "Município de Itapissuma",
            "Município de Itaquitinga",
            "Município de Jaboatão dos Guararapes",
            "Município de Jaqueira",
            "Município de Jataúba",
            "Município de João Alfredo",
            "Município de Joaquim Nabuco",
            "Município de Jucati",
            "Município de Jupi",
            "Município de Jurema",
            "Município de Lagoa de Itaenga",
            "Município de Lagoa do Carro",
            "Município de Lagoa do Ouro",
            "Município de Lagoa dos Gatos",
            "Município de Lagoa Grande",
            "Município de Lajedo",
            "Município de Limoeiro",
            "Município de Macaparana",
            "Município de Machados",
            "Município de Manari",
            "Município de Maraial",
            "Município de Mirandiba",
            "Município de Moreilândia",
            "Município de Moreno",
            "Município de Olinda",
            "Município de Orobó",
            "Município de Orocó",
            "Município de Ouricuri",
            "Município de Panelas",
            "Município de Paranatama",
            "Município de Parnamirim",
            "Município de Passira",
            "Município de Paulista",
            "Município de Pedra",
            "Município de Pesqueira",
            "Município de Petrolândia",
            "Município de Poção",
            "Município de Pombos",
            "Município de Quipapá",
            "Município de Quixaba",
            "Município de Recife",
            "Município de Riacho das Almas",
            "Município de Ribeirão",
            "Município de Rio Formoso",
            "Município de Sairé",
            "Município de Salgadinho",
            "Município de Salgueiro",
            "Município de Saloá",
            "Município de Sanharó",
            "Município de Santa Cruz da Baixa Verde",
            "Município de Santa Cruz do Capibaribe",
            "Município de Santa Maria da Boa Vista",
            "Município de Santa Maria do Cambucá",
            "Município de Santa Terezinha",
            "Município de São Benedito do Sul",
            "Município de São Bento do Una",
            "Município de São Caitano",
            "Município de São João",
            "Município de São Joaquim do Monte",
            "Município de São José da Coroa Grande",
            "Município de São José do Belmonte",
            "Município de São José do Egito",
            "Município de São José do Egito - ACORDO",
            "Município de São Lourenço da Mata",
            "Município de São Vicente Férrer",
            "Município de Serra Talhada",
            "Município de Sertânia",
            "Município de Solidão",
            "Município de Surubim",
            "Município de Tabira",
            "Município de Tacaimbó",
            "Município de Tacaratu",
            "Município de Tamandaré",
            "Município de Terra Nova",
            "Município de Timbaúba",
            "Município de Toritama",
            "Município de Trindade",
            "Município de Tupanatinga",
            "Município de Venturosa",
            "Município de Verdejante",
            "Município de Vicência",
            "Município de Vitória de Santo Antão",
            "Município de Xexéu",
            "PASSIRAPREV Instituto de Previdência do Município de Passira",
            "QUIPAPAPREV Fundo de Previdência dos Servidores Municipais de Quipapá",
            "RECIPREV S Autarquia Municipal de Previdência e Assistência à Saúde dos Servidores do Município do Recife",
            "SAAE Serviço Autônomo de Água e Esgoto do Município de Água Preta",
            "SANTA CRUZ PREV Regime Próprio de Previdência Social do Município de Santa Cruz do Capibaribe",
            "URB - Empresa de Urbanização Planejamento e Meio Ambiente do Município de CARUARU",
            "URB - Empresa de Urbanização do Recife",
        ],
        ESPECIAL: [
            "ESTADO DE PERNAMBUCO",
            "CAMUTANGA",
            "CARPINA",
            "CUSTÓDIA",
            "GOIANA",
            "IATI",
            "IGARASSU",
            "PALMARES",
            "PALMEIRINA",
            "PAUDALHO",
            "PETROLINA",
            "PRIMAVERA",
            "TRACUNHAÉM",
        ]
    },
    PI: {
        COMUM: [
            "MUNICÍPIO DE ALTOS",
            "MUNICÍPIO DE ÁGUA BRANCA",
            "MUNICÍPIO DE ALAGOINHA DO PIAUÍ",
            "MUNICÍPIO DE ARRAIAL",
            "MUNICÍPIO DE BARRO DURO",
            "MUNICÍPIO DE BATALHA",
            "MUNICÍPIO DE BOM PRINCÍPIO DO PIAUÍ",
            "MUNICÍPIO DE BONFIM DO PIAUÍ",
            "MUNICÍPIO DE BURITI DOS LOPES",
            "MUNICÍPIO DE CANAVIEIRA",
            "MUNICÍPIO DE CAPITÃO GERVÁSIO OLIVEIRA",
            "MUNICÍPIO DE CRISTINO CASTRO",
            "MUNICÍPIO DE DOM EXPEDITO LOPES",
            "MUNICÍPIO DE ESPERANTINA",
            "MUNICÍPIO DE FLORIANO",
            "MUNICÍPIO DE GEMINIANO",
            "MUNICÍPIO DE GUADALUPE",
            "MUNICÍPIO DE ILHA GRANDE",
            "MUNICÍPIO DE ITAUEIRA",
            "MUNICÍPIO DE JACOBINA DO PIAUÍ",
            "MUNICÍPIO DE JUAZEIRO DO PIAUÍ",
            "MUNICÍPIO DE NOSSA SENHORA DE NAZARÉ",
            "MUNICÍPIO DE NOSSA SENHORA DOS REMÉDIOS",
            "MUNICÍPIO DE PARNAÍBA",
            "MUNICÍPIO DE PEDRO II",
            "MUNICÍPIO DE PEDRO LAURENTINO",
            "MUNICÍPIO DE PRATA DO PIAUÍ",
            "MUNICÍPIO DE REGENERAÇÃO",
            "MUNICÍPIO DE RIACHO FRIO",
            "MUNICÍPIO DE SÃO MIGUEL DA BAIXA GRANDE",
            "MUNICÍPIO DE SÃO JOÃO DA CANABRAVA",
            "MUNICÍPIO DE SANTA CRUZ DO PIAUÍ",
            "MUNICÍPIO DE SIGEFREDO PACHECO",
            "MUNICÍPIO DE UNIÃO",
            "MUNICÍPIO DE VALENÇA DO PIAUÍ",
            "MUNICÍPIO DE VÁRZEA BRANCA",
            "MUNICÍPIO DE SÃO JOÃO DO ARRAIAL",
            "MUNICÍPIO DE FLORESTA DO PIAUÍ",
            "MUNICÍPIO DE URUÇUÍ",
            "MUNICÍPIO DE JOÃO COSTA",
            "MUNICÍPIO DE SÃO MIGUEL DO TAPUIO",
            "MUNICÍPIO DE PORTO",
            "MUNICÍPIO DE NOVA SANTA RITA",
            "MUNICÍPIO DE MARCOLÂNDIA",
            "MUNICÍPIO DE BENEDITINOS",
            "MUNICÍPIO DE SIMÕES",
            "MUNICÍPIO DE CURRALINHOS",
            "MUNICÍPIO DE CAMPO LARGO DO PIAUÍ",
            "MUNICÍPIO DE BOQUEIRÃO DO PIAUÍ",
            "MUNICÍPIO DE FRANCISCO MACEDO",
            "MUNICÍPIO DE FRANCISCO SANTOS",
            "MUNICÍPIO DE CAXINGÓ",
            "MUNICÍPIO DE BOCAINA",
            "MUNICÍPIO DE LAGOA DO PIAUÍ",
            "MUNICÍPIO DE BOA HORA",
            "MUNICÍPIO DE MARCOS PARENTE",
            "MUNICÍPIO DE JARDIM DO MULATO",
            "MUNICÍPIO DE DOM INOCÊNCIO",
            "MUNICÍPIO DE JOAQUIM PIRES",
            "MUNICÍPIO DE JOSÉ DE FREITAS",
            "INST. PREV. MUN. PARNAÍBA - IPMP",
            "MUNICÍPIO DE NAZARÉ DO PIAUÍ",
            "INSTITUTO DE PREVIDÊNCIA MUNICIPAL DE TERESIN",
            "MUNICÍPIO DE LANDRI SALES",
            "MUNICÍPIO DE JERUMENHA",
            "MUNICÍPIO DE CALDEIRÃO GRANDE DO PIAUÍ",
            "MUNICÍPIO DE CARIDADE DO PIAUÍ",
            "MUNICÍPIO DE NOVO SANTO ANTÔNIO",
            "MUNICÍPIO DE DOMINGOS MOURÃO",
            "MUNICÍPIO DE ALVORADA DO GURGUÉIA",
            "MUNICÍPIO DE REDENÇÃO DO GURGUÉIA",
            "MUNICÍPIO DE SÃO PEDRO DO PIAUÍ",
        ],
        ESPECIAL: [
            "MUNICÍPIO DE ALTO LONGÁ",
            "MUNICÍPIO DE AMARANTE",
            "MUNICÍPIO DE ANGICAL DO PIAUÍ",
            "MUNICÍPIO DE AROAZES",
            "MUNICÍPIO DE BARRAS",
            "MUNICÍPIO DE CAMPO MAIOR",
            "MUNICÍPIO DE CORRENTE",
            "MUNICÍPIO DE CARACOL",
            "MUNICÍPIO DE DEMERVAL LOBÃO",
            "MUNICÍPIO DE DIRCEU ARCOVERDE",
            "ESTADO DO PIAUÍ",
            "MUNICÍPIO DE FARTURA DO PIAUÍ",
            "MUNICÍPIO DE FLORES DO PIAUÍ",
            "MUNICÍPIO DE JATOBÁ DO PIAUÍ",
            "MUNICÍPIO DE LUZILÂNDIA",
            "MUNICÍPIO DE MATIAS OLÍMPIO",
            "MUNICÍPIO DE NOVO ORIENTE DO PIAUÍ",
            "MUNICÍPIO DE OEIRAS",
            "MUNICÍPIO DE PAULISTANA",
            "MUNICÍPIO DE PICOS",
            "MUNICÍPIO DE PARNAGUÁ",
            "MUNICÍPIO DE PAVUSSU",
            "MUNICÍPIO DE PIMENTEIRAS",
            "MUNICÍPIO DE PIRACURUCA",
            "MUNICÍPIO DE SÃO BRAZ DO PIAUÍ",
            "MUNICÍPIO DE SÃO JOÃO DO PIAUÍ",
            "MUNICÍPIO DE SÃO JOÃO DA SERRA",
            "MUNICÍPIO DE TERESINA",
            "MUNICÍPIO DE MADEIRO",
            "MUNICÍPIO DE MONSENHOR GIL",
            "MUNICÍPIO DE LAGOA ALEGRE",
            "MUNICÍPIO DE MONSENHOR HIPÓLITO",
            "MUNICÍPIO DE COCAL",
            "MUNICÍPIO DE INHUMA",
            "MUNICÍPIO DE ITAINÓPOLIS",
            "MUNICÍPIO DE PADRE MARCOS",
            "MUNICÍPIO DE CRISTALÂNDIA DO PIAUÍ",
            "MUNICÍPIO DE CURRAIS",
            "MUNICÍPIO DE RIO GRANDE DO PIAUÍ",
            "MUNICÍPIO DE MANOEL EMÍDIO",
            "MUNICÍPIO DE SÃO RAIMUNDO NONATO",
        ]
    }
};
