const EstadoRegimeEnteDevedorRobson = {
    AC: {
        COMUM: [
            'MUNICÍPIO DE BUJARI',
            'MUNICÍPIO DE EPITACIOLÂNDIA',
            'MUNICÍPIO DE FEIJÓ',
            'MUNICÍPIO DE JORDÃO',
            'MUNICÍPIO DE MÂNCIO LIMA',
            'MUNICÍPIO DE MANOEL URBANO',
            'MUNICÍPIO DE PORTO WALTER',
            'MUNICÍPIO DE RODRIGUES ALVES',
            'MUNICÍPIO DE SANTA ROSA DO PURUS',
        ],
        ESPECIAL: [
            'DEPARTAMENTO ESTADUAL DE PAVIMENTAÇÃO ESANEAMENTO -DEAS',
            'DEPARTAMENTO DE ESTRADAS DE RODAGEM, INFRAESTRUTUTRA HIDROVIÁRIA E AEROPORTUÁRIA DO ACRE - DERACRE',
            'DEPARTAMENTO ESTADUAL DE TRÂNSITO DO ESTADO DOACRE - DETRAN/AC',
            'EMPRESA DE PROCESSAMENTO DE DADOS DO ACRE - ACREDATA',
            'EMPRESA DE ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL DOESTADO DO ACRE - EMATER',
            'FUNDAÇÃO DE APOIO DO DESENVOLVIMENTO ECONÔMICO ESOCIAL - FADES',
            'FUNDAÇÃO DE CULTURA E COMUNICAÇÃO ELIAS MANSOUR -FEM',
            'FUNDAÇÃO DO BEM ESTAR SOCIAL DO ACRE - FUNBESA',
            'FUNDAÇÃO HOSPITAL ESTADUAL DO ACRE - FUNDHACRE',
            'INSTITUTO DE DEFESA AGROPECUÁRIA E FLORESTAL DO ACRE - IDAF',
            'FUNDAÇÃO DE DESENVOLVIMENTO DE RECURSOS HUMANOS DA CULTURA E DO DESPORTO - FDRHCD',
            'FUNDAÇÃO DE TECNOLOGIA DO ESTADO DO ACRE - FUNTAC',
            'INSTITUTO DE MEIO AMBIENTE DO ACRE - IMAC',
            'INSTITUTO DE PREVIDÊNCIA DO ESTADO DO ACRE - ACREPREVIDÊNCIA',
            'INSTITUTO DE ADMINISTRAÇÃO PENITENCIÁRIA DO ESTADO DOACRE - IAPEN/AC',
            'INSTITUTO ESTADUAL DE DESENVOLVIMENTO DA EDUCAÇÃO PROFISSIONAL DOM MOACIR GRECHI',
            'INSTITUTO SOCIO EDUCATIVO DO ESTADO DO ACRE - ISE',
            'MUNICÍPIO DE ACRELÂNDIA',
            'MUNICÍPIO DE ASSIS BRASIL',
            'MUNICÍPIO DE BRASILÉIA',
            'MUNICÍPIO DE CAPIXABA',
            'MUNICÍPIO DE CRUZEIRO DO SUL',
            'MUNICÍPIO DE MARECHAL THAUMATURGO',
            'MUNICÍPIO DE PLÁCIDO DE CASTRO',
            'MUNICÍPIO DE PORTO ACRE',
            'MUNICÍPIO DE RIO BRANCO',
            'SERVIÇO DE ÁGUA E ESGOSTO DE RIO BRANCO - SAERB',
            'EMPRESA MUNICIPAL DE URBABIZAÇÃO DE RIO BRANCO - EMURB',
            'FUNDAÇÃO MUNICIPAL DE CULTURA GARIBALDI BRASIL - FMCGB',
            'MUNICÍPIO DE SENA MADUREIRA',
            'MUNICÍPIO DE SENADOR GUIOMARD',
            'MUNICÍPIO DE TARAUACÁ',
            'MUNICÍPIO DE XAPURI',
        ],
    },
    AL: {
        COMUM: [
            'ADEAL',
            'ARSAL - AGÊNCIA REGULADORA DE SERVIÇOS PÚBLICOS DO ESTADO DE ALAGOAS',
            'AGUA BRANCA',
            'ALAGOAS PREVIDÊNCIA',
            'ARAPIRACA',
            'ASSEMBLEIA LEGISLATIVA',
            'ATALAIA',
            'BARRA DE SANTO ANTONIO',
            'BARRA DE SÃO MIGUEL',
            'BATALHA',
            'BELÉM',
            'BOCA DA MATA',
            'CASAL',
            'CHÃ PRETA',
            'CACIMBINHAS',
            'CAJUEIRO',
            'CAMPESTRE',
            'CAMPO ALEGRE',
            'CAMPO GRANDE',
            'CAPELA',
            'CARNEIROS',
            'CARNEIROS',
            'COLÔNIA DE LEOPOLDINA',
            'COQUEIRO SECO',
            'CORURIPE',
            'CORURIPE',
            'CRAÍBAS',
            'DER',
            'DETRAN',
            'DOIS RIACHOS',
            'ESTADO DE ALAGOAS',
            'ESTRELA DE ALAGOAS',
            'FAPEN - FUNDO DE APOSENTADORIA E PENSÕES DE SÃO JOSÉ DA LAJE',
            'FAPEN - FUNDO DE PREVIDÊNCIA DE MURICI',
            'FUNPREMA - FUNDO DE PREVIDÊNCIA DO MUNICÍPIO DE MARIBONDO',
            'FAPEN - CAJUEIRO',
            'FEIRA GRANDE',
            'GIRAU DO PONCIANO',
            'IMA-INSTITUTO DO MEIO AMBIENTE DE ALAGOAS',
            'INSS',
            'IPASEAL-SAÚDE',
            'IPSEMG - INSTITUTO DE PREVIDÊNCIA DO MUNICÍPIO DE MATA GRANDE',
            'ITEC - INSTITUTO DE TECNOLOGIA EM INFORMÁTICA E INFORMAÇÃO DO ESTADO DE ALAGOAS',
            'ITERAL - INSTITUTO DE TERRAS E REFORMA AGRÁRIA DO ESTADO DE ALAGOAS',
            'IBATEGUARA',
            'IGACI',
            'INHAPI',
            'INSTITUTO DE PREVIDÊNCIA DO MUNICÍPIO DE PALMEIRA DOS ÍNDIOS',
            'JACUÍPE',
            'JAPARATINGA',
            'JEQUIÁ DA PRAIA',
            'JOAQUIM GOMES',
            'JUNQUEIRO',
            'LAGOA DA CANOA',
            'LIMOEIRO DE ANADIA',
            'MARAGOGI',
            'MARAVILHA',
            'MARECHAL DEODORO',
            'MARIBONDO',
            'MATA GRANDE',
            'MATRIZ DE CAMARAGIBE',
            'MESSIAS',
            'MURICI',
            'NOVO LINO',
            "OLHO D'AGUA GRANDE",
            "OLHO D'AGUA DAS FLORES",
            "OLHO D'AGUA DO CASADO",
            'OLIVENÇA',
            'PORTOPREVI - INST. DE PREV. DO MUN. DE PORTO CALVO',
            'PALMEIRA DOS ÍNDIOS',
            'PARIPUEIRA',
            'PASSO DE CAMARAGIBE',
            'PAULO JACINTO',
            'PENEDO',
            'PIAÇABUÇU',
            'PIRANHAS',
            'PORTO CALVO',
            'PORTO REAL DO COLÉGIO',
            'PÃO DE AÇUCAR',
            'QUEBRANGULO',
            'RIO LARGO',
            'ROTEIRO',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO - BOCA DA MATA/AL',
            'SAE - SERVIÇO DE ÁGUA E ESGOTO DE PORTO REAL DO COLÉGIO',
            'SAE - SERVIÇO DE ÁGUA E ESGOTO DE UNIÃO DOS PALMARES',
            'SMTT - SUPERINTENDÊNCIA MUNICIPAL DE TRANSPORTE E TRÂNSITO DE ARAPIRACA/AL',
            'SANTA LUZIA DO NORTE',
            'SANTANA DO IPANEMA',
            'SANTANA DO MUNDAÚ',
            'SENADOR RUI PALMEIRA',
            'SÃO BRÁS',
            'SÃO JOSÉ DA LAJE',
            'SÃO JOSÉ DA TAPERA',
            'SÃO LUÍS DO QUITUNDE',
            'SÃO MIGUEL DOS CAMPOS',
            'SÃO MIGUEL DOS MILAGRES',
            'SÃO SEBASTIÃO',
            'TANQUE DARCA',
            'TAQUARANA',
            'TEOTÔNIO VILELA',
            'TRAIPU',
            'UNCISAL',
            'UNEAL – UNIVERSIDADE ESTADUAL DE ALAGOAS',
            'VIÇOSA',
        ],
        ESPECIAL: ['Anadia', 'Canapi', 'Delmiro Gouveia', 'Maceió', 'União dos Palmares'],
    },
    AP: {
        COMUM: [
            'AMAPA',
            'CALCOENE',
            'PEDRA BRANCA',
            'SERRA DO NAVIO',
            'TARTARUGALZINHO',
            'VITORIA DO JARI',
        ],
        ESPECIAL: [
            'MACAPA',
            'SANTANA',
            'LARANJAL DO JARI',
            'CUTIAS',
            'FERREIRA GOMES',
            'ITAUBAL',
            'MAZAGAO',
            'OIAPOQUE',
            'PORTO GRANDE',
            'PRACUUBA',
        ],
    },
    AM: {
        COMUM: [
            'Estado do Amazonas',
            'Município de Alvarães',
            'Município de Amaturá',
            'Município de Anamã',
            'Município de Anori',
            'Município de Apuí',
            'Município de Atalaia do Norte',
            'Município de Autazes',
            'Município de Barreirinha',
            'Município de Beruri',
            'Município de Caapiranga',
            'Município de Canutama',
            'Município de Caruaru',
            'Município de Careiro',
            'Município de Codajás',
            'Município de Eirunepé',
            'Município de Envira',
            'Município de Fonte Boa',
            'Município de Humaitá',
            'Município de Ipixuna',
            'Município de Iranduba',
            'Município de Itacoatiara',
            'Município de Itamarati',
            'Município de Itapiranga',
            'Município de Japurá',
            'Município de Jutaí',
            'Município de Lábrea',
            'Município de Manacapuru',
            'Município de Maraã',
            'Município de Manicoré Município de Maués',
            'Município de Nhamundá',
            'Município de Nova Olinda do Norte',
            'Município de Novo Airão',
            'Município de Novo Airipuanã',
            'Município de Parintins',
            'Município de Pauini',
            'Município de Presidente Figueiredo',
            'Município de Santo Antônio do Iça',
            'Município de São Sebastião do Uatumã',
            'Município de Silves',
            'Município de Tabatinga',
            'Município de Tapuá',
            'Município de Tefé',
            'Município de Uarini',
            'Município de Rio Preto da Eva',
            'Município de São Gabriel da Cachoeira',
            'Município de São Paulo de Olivença',
            'Câmara Municipal de Coari',
            'CETAM',
            'Companhia de Água, Esgoto e Saneamento básico de Coari',
            'Companhia de Saneamento do Amazonas - Cosama',
            'Departamento de Trânsito - Detran',
            'Fundação Amazonprev',
            'Fundação Centro de Controle de Oncologia do Estado do Amazonas - FCECON',
            'Fundação de Apoio ao Idoso Doutor Thomas',
            'Fundação de Dermatologia Tropical e Venereologia Alfredo da Matta - FUAM',
            'Fundação de Hematologia e Hemoterapia do Amazonas - HEMOAM',
            'Fundação de Medicina Tropical - FMT',
            'Fundação de Vigilância em Saúde - FVS',
            'Fundação Hospital Adriano Jorge',
            'Fundação Universidade do Amazonas - FUA',
            'Fundo Municipal de Previdência e Assistência Social - FUMPAS',
            'Instituto de Desenvolvimento Agropecuário e Florestal Sustentável do Amazonas - IDAM',
            'Instituto de Proteção Ambiental do Amazonas - IPAAM',
            'Instituto e Previdência do Município de Coari',
            'Instituto Municipal de Mobilidade Urbana - IMMU',
            'Instituto Municipal de Planejamento Urbano - IMPLURB',
            'Junta Comercial do Estado do Amazonas - JUCEA',
            'Manaus Previdencia - Manausprev',
            'Município de Manacapuru - Serviço autonomo de água e esgoto - SAAE',
            'Municipio de Rio Preto da Eva - Serviço Autônomo de Água e Esgoto de Rio Preto da Eva - SAAE',
            'Superintendência Estadual de Habitação - SUHAB',
            'Superintendência Estadual de Navegação, Portos e Hidrovias - SNPH',
            'Superintendência Municipal de Transportes Urbanos - SMTU',
            'Universidade do Estado do Amazonas - UEA',
            'Universidade do Estado do Rio de Janeiro - UERJ',
        ],
        ESPECIAL: ['Município de Manaus', 'Município de Coari'],
    },
    BA: {
        COMUM: [
            'MUNICIPIO DE ADUSTINA',
            'MUNICIPIO DE AGUA FRIA',
            'MUNICIPIO DE ANGICAL',
            'MUNICIPIO DE ANTONIO CARDOSO',
            'MUNICIPIO DE APORA',
            'MUNICIPIO DE ARACI',
            'MUNICÍPIO DE ARATACA',
            'MUNICIPIO DE BAIANOPOLIS',
            'MUNICIPIO DE BAIXA GRANDE',
            'MUNICIPIO DE BANZAE',
            'MUNICIPIO DE BARRA DO ROCHA',
            'MUNICÍPIO DE BARRA DO ROCHA',
            'MUNICÍPIO DE BARRO PRETO',
            'MUNICÍPIO DE BIRITINGA',
            'MUNICÍPIO DE BOM JESUS DA SERRA',
            'MUNICÍPIO DE BOQUIRA',
            'MUNICÍPIO DE CAÉM',
            'MUNICÍPIO DE CAETITÉ',
            'MUNICÍPIO DE CAFARNAUM',
            'MUNICIPIO DE CAMACARI',
            'MUNICIPIO DE CANAPOLIS',
            'MUNICÍPIO DE CARAVELAS',
            'MUNICIPIO DE CATU',
            'MUNICÍPIO DE CENTRAL',
            'MUNICIPIO DE CICERO DANTAS',
            'MUNICIPIO DE CIPO',
            'MUNICIPIO DE CONCEICAO DO JACUIPE',
            'MUNICIPIO DE CORACAO DE MARIA',
            'MUNICIPIO DE CORRENTINA',
            'MUNICÍPIO DE CRISTÓPOLIS',
            'MUNICIPIO DE CURACA',
            'MUNICÍPIO DE ENCRUZILHADA',
            'MUNICIPIO DE ENTRE RIOS',
            'MUNICIPIO DE ESPLANADA',
            'MUNICIPIO DE EUCLIDES DA CUNHA',
            'MUNICIPIO DE FATIMA',
            'MUNICIPIO DE FEIRA DE SANTANA',
            'MUNICIPIO DE GLORIA',
            'MUNICIPIO DE GUANAMBI',
            'MUNICIPIO DE GUARATINGA',
            'MUNICIPIO DE HELIOPOLIS',
            'MUNICÍPIO DE IBIRAPUÃ',
            'MUNICIPIO DE IBIRATAIA',
            'MUNICIPIO DE IBITITA',
            'MUNICÍPIO DE IGUAÍ',
            'MUNICIPIO DE IPECAETA',
            'MUNICIPIO DE ITAMARI',
            'MUNICIPIO DE ITANHEM',
            'MUNICIPIO DE ITAPARICA',
            'MUNICIPIO DE ITAPITANGA',
            'MUNICIPIO DE ITAQUARA',
            'MUNICIPIO DE ITIUBA',
            'MUNICÍPIO DE ITUBERÁ',
            'MUNICIPIO DE JACOBINA',
            'MUNICIPIO DE JAGUAQUARA',
            'MUNICIPIO DE JEQUIE',
            'MUNICIPIO DE JIQUIRICA',
            'MUNICIPIO DE JUCURUCU',
            'MUNICIPIO DE JUSSARA',
            'MUNICIPIO DE LAJEDAO',
            'MUNICIPIO DE LAJEDINHO',
            'MUNICIPIO DE LAURO DE FREITAS',
            'MUNICIPIO DE LIVRAMENTO DE NOSSA SENHORA',
            'MUNICIPIO DE LUIS EDUARDO MAGALHAES',
            'MUNICÍPIO DE MACAJUBA',
            'MUNICIPIO DE MACARANI',
            'MUNICIPIO DE MAIQUINIQUE',
            'MUNICIPIO DE MARAGOGIPE',
            'MUNICIPIO DE MASCOTE',
            'MUNICÍPIO DE MONTE SANTO',
            'MUNICÍPIO DE MUCURI',
            'MUNICÍPIO DE MUNIZ FERREIRA',
            'MUNICIPIO DE MURITIBA',
            'MUNICIPIO DE NOVA VICOSA',
            'MUNICIPIO DE NOVO TRIUNFO',
            'MUNICÍPIO DE NOVO HORIZONTE',
            'MUNICIPIO DE OLINDINA',
            'MUNICÍPIO DE OUROLÂNDIA',
            'MUNICIPIO DE PALMEIRAS',
            'MUNICIPIO DE PAULO AFONSO',
            'MUNICÍPIO DE PEDRO ALEXANDRE',
            'MUNICÍPIO DE PILÃO ARCADO',
            'MUNICIPIO DE PINDOBACU',
            'MUNICIPIO DE PORTO SEGURO',
            'MUNICÍPIO DE RAFAEL JAMBEIRO',
            'MUNICIPIO DE RETIROLÂNDIA',
            'MUNICÍPIO DE RIACHÃO DO JACUÍPE',
            'MUNICIPIO DE RIBEIRA DO AMPARO',
            'MUNICIPIO DE RIBEIRA DO POMBAL',
            'MUNICÍPIO DE RIBEIRÃO DO LARGO',
            'MUNICIPIO DE SANTA LUZIA',
            'MUNICÍPIO DE SANTA MARIA DA VITÓRIA',
            'MUNICÍPIO DE SANTO ANTÔNIO DE JESUS',
            'MUNICÍPIO DE SÃO GABRIEL',
            'MUNICIPIO DE SAO FRANCISCO DO CONDE',
            'MUNICIPIO DE SEABRA',
            'MUNICIPIO DE SENHOR DO BONFIM',
            'MUNICIPIO DE SERRA DO RAMALHO',
            'MUNICIPIO DE SERRINHA',
            'MUNICÍPIO DE SOBRADINHO',
            'MUNICIPIO DE TANHACU',
            'MUNICÍPIO DE TEIXEIRA DE FREITAS',
            'MUNICÍPIO DE TREMEDAL',
            'MUNICIPIO DE UAUÁ',
            'MUNICÍPIO DE UNA',
            'MUNICIPIO DE VERA CRUZ',
            'MUNICIPIO DE VITORIA DA CONQUISTA',
            'MUNICÍPIO DE WENCESLAU GUIMARÃES',
            'PREVIS INSTITUTO DE PREVIDENCIA DO SALVADOR',
            'SAAE - SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO VALENÇA',
        ],
        ESPECIAL: [
            'ESTADO DA BAHIA',
            'MUNICÍPIO DE  VITÓRIA DA CONQUISTA',
            'MUNICÍPIO DE CONTENDAS  DO SINCORÁ',
            'MUNICÍPIO DE SÃO FRANCISCO DO CONDE',
            'MUNICÍPIO DE ANAGÉ',
            'MUNICÍPIO DE AURELINO LEAL',
            'MUNICÍPIO DE BARREIRAS',
            'MUNICÍPIO DE BARRO PRETO',
            'MUNICÍPIO DE BELMONTE',
            'MUNICÍPIO DE BUERAREMA',
            'MUNICÍPIO DE CAATIBA',
            'MUNICÍPIO DE CACHOEIRA',
            'MUNICÍPIO DE CAMACAN',
            'MUNICÍPIO DE CAMAÇARI',
            'MUNICÍPIO DE CAMAMÚ',
            'MUNICÍPIO DE CANARANA',
            'MUNICÍPIO DE CANAVIEIRAS',
            'MUNICÍPIO DE CANDEAL',
            'MUNICÍPIO DE CÂNDIDO SALES',
            'MUNICÍPIO DE CANUDOS',
            'MUNICÍPIO DE CARAÍBAS',
            'MUNICÍPIO DE CASA NOVA',
            'MUNICÍPIO DE CATURAMA',
            'MUNICÍPIO DE COARACI',
            'MUNICÍPIO DE COTEGIPE',
            'MUNICÍPIO DE ESPLANADA',
            'MUNICÍPIO DE EUNÁPOLIS',
            'MUNICÍPIO DE FIRMINO ALVES',
            'MUNICÍPIO DE FLORESTA AZUL',
            'MUNICÍPIO DE GONGOGI',
            'MUNICÍPIO DE IAÇÚ',
            'MUNICÍPIO DE IBIASSUCÊ',
            'MUNICÍPIO DE IBICARAÍ',
            'MUNICÍPIO DE IBIRAPITANGA',
            'MUNICÍPIO DE ILHÉUS',
            'MUNICÍPIO DE IPIRÁ',
            'MUNICÍPIO DE ITABUNA',
            'MUNICÍPIO DE ITAGI',
            'MUNICÍPIO DE ITAGIMIRIM',
            'MUNICÍPIO DE ITAJÚ DO COLÔNIA',
            'MUNICÍPIO DE ITAJUÍPE',
            'MUNICÍPIO DE ITAMARAJÚ',
            'MUNICÍPIO DE ITAMBÉ',
            'MUNICÍPIO DE ITAPÉ',
            'MUNICÍPIO DE ITIRUÇÚ',
            'MUNICÍPIO DE ITORORÓ',
            'MUNICÍPIO DE JAGUARARI',
            'MUNICÍPIO DE JANDAÍRA',
            'MUNICÍPIO DE JITAÚNA',
            'MUNICÍPIO DE JUAZEIRO',
            'MUNICÍPIO DE MAIRI',
            'MUNICÍPIO DE MIGUEL CALMON',
            'MUNICÍPIO DE MUTUÍPE',
            'MUNICÍPIO DE NOVA ITARANA',
            'MUNICÍPIO DE PARIPIRANGA',
            'MUNICÍPIO DE PAU BRASIL',
            'MUNICÍPIO DE PÉ DE SERRA',
            'MUNICÍPIO DE PLANALTO',
            'MUNICÍPIO DE POÇÕES',
            'MUNICÍPIO DE PONTO NOVO',
            'MUNICÍPIO DE QUEIMADAS',
            'MUNICÍPIO DE QUIJINGUE',
            'MUNICÍPIO DE REMANSO',
            'MUNICÍPIO DE RIO DO ANTÔNIO',
            'MUNICÍPIO DE SALVADOR',
            'MUNICÍPIO DE SANTA BRÍGIDA',
            'MUNICÍPIO DE SANTO AMARO',
            'MUNICÍPIO DE SÃO FÉLIX',
            'MUNICÍPIO DE SÁTIRO DIAS',
            'MUNICÍPIO DE SAÚDE',
            'MUNICÍPIO DE SENTO SÉ',
            'MUNICÍPIO DE SERROLÂNDIA',
            'MUNICÍPIO DE SIMÕES FILHO',
            'MUNICÍPIO DE SÍTIO DO MATO',
            'MUNICÍPIO DE SOBRADINHO',
            'MUNICÍPIO DE TABOCAS DO BREJO VELHO',
            'MUNICÍPIO DE TANQUE NOVO',
            'MUNICÍPIO DE TAPEROÁ',
            'MUNICÍPIO DE TEOFILÂNDIA',
            'MUNICÍPIO DE UBAITABA',
            'MUNICÍPIO DE URANDI',
            'MUNICÍPIO DE URUÇUCA',
            'MUNICÍPIO DE VALENÇA',
            'MUNICÍPIO DE VÁRZEA DO POÇO',
            'SÃO JOSÉ DA VITÓRIA',
        ],
    },
    CE: {
        COMUM: [
            'MUNICÍPIO DE ABAIARA',
            'MUNICÍPIO DE ACOPIARA',
            'MUNICÍPIO DE AIUABA',
            'MUNICÍPIO DE ALTANEIRA',
            'MUNICÍPIO DE AMONTADA',
            'MUNICÍPIO DE AQUIRAZ',
            'MUNICÍPIO DE ARACATI',
            'MUNICÍPIO DE ARACOIABA',
            'MUNICÍPIO DE ARARIPE',
            'MUNICÍPIO DE ARARENDÁ',
            'MUNICÍPIO DE ARATUBA',
            'MUNICÍPIO DE ARNEIROZ',
            'MUNICÍPIO DE BARBALHA',
            'MUNICÍPIO DE BARROQUINHA',
            'MUNICÍPIO DE BEBERIBE',
            'MUNICÍPIO DE BOA VIAGEM',
            'MUNICÍPIO DE BREJO SANTO',
            'MUNICÍPIO DE CAMOCIM',
            'MUNICÍPIO DE CAMPOS SALES',
            'MUNICÍPIO DE CAPISTRANO',
            'MUNICÍPIO DE CARIDADE',
            'MUNICÍPIO DE CARIRIAÇU',
            'MUNICÍPIO DE CARIÚS',
            'MUNICÍPIO DE CARNAUBAL',
            'MUNICÍPIO DE CASCAVEL',
            'MUNICÍPIO DE CATARINA',
            'MUNICÍPIO DE CATUNDA',
            'MUNICÍPIO DE CAUCAIA',
            'MUNICÍPIO DE CEDRO',
            'MUNICÍPIO DE CHAVAL',
            'MUNICÍPIO DE CHORÓ',
            'MUNICÍPIO DE CHOROZINHO',
            'MUNICÍPIO DE CRATO',
            'MUNICÍPIO DE CRATEÚS',
            'MUNICÍPIO DE ERERÊ',
            'MUNICÍPIO DE FORQUILHA',
            'MUNICÍPIO DE FRECHEIRINHA',
            'MUNICÍPIO DE GENERAL SAMPAIO',
            'MUNICÍPIO DE GRAÇA',
            'MUNICÍPIO DE GROAÍRAS',
            'MUNICÍPIO DE GUARACIABA DO NORTE',
            'MUNICÍPIO DE HIDROLANDIA',
            'MUNICÍPIO DE HORIZONTE',
            'MUNICÍPIO DE IBARETAMA',
            'MUNICÍPIO DE IBICUITINGA',
            'MUNICÍPIO DE ICAPUÍ',
            'MUNICÍPIO DE ICO',
            'MUNICÍPIO DE IGUATU',
            'MUNICÍPIO DE IPAPORANGA',
            'MUNICÍPIO DE IPÚ',
            'MUNICÍPIO DE IPUEIRAS',
            'MUNICÍPIO DE IRACEMA',
            'MUNICÍPIO DE ITAITINGA',
            'MUNICÍPIO DE ITAPAJÉ',
            'MUNICÍPIO DE ITAPIPOCA',
            'MUNICÍPIO DE ITAPIUNA',
            'MUNICÍPIO DE ITAREMA',
            'MUNICÍPIO DE ITATIRA',
            'MUNICÍPIO DE JAGUARETAMA',
            'MUNICÍPIO DE JAGUARIBARA',
            'MUNICÍPIO DE JAGUARIBE',
            'MUNICÍPIO DE JAGUARUANA',
            'MUNICÍPIO DE JUAZEIRO DO NORTE',
            'MUNICÍPIO DE LAVRAS DA MANGABEIRA',
            'MUNICÍPIO DE MADALENA',
            'MUNICÍPIO DE MARACANAU',
            'MUNICÍPIO DE MARANGUAPE',
            'MUNICÍPIO DE MASSAPÊ',
            'MUNICÍPIO DE MAURITI',
            'MUNICÍPIO DE MILHÃ',
            'MUNICÍPIO DE MOMBAÇA',
            'MUNICÍPIO DE MONSENHOR TABOSA',
            'MUNICÍPIO DE MORADA NOVA',
            'MUNICÍPIO DE MORRINHOS',
            'MUNICÍPIO DE MUCAMBO',
            'MUNICÍPIO DE MULUNGU',
            'MUNICÍPIO DE NOVA OLINDA',
            'MUNICÍPIO DE NOVA RUSSAS',
            'MUNICÍPIO DE NOVO ORIENTE',
            'MUNICÍPIO DE PACAJUS',
            'MUNICÍPIO DE PACATUBA',
            'MUNICÍPIO DE PACOTI',
            'MUNICÍPIO DE PALHANO',
            'MUNICÍPIO DE PARACURU',
            'MUNICÍPIO DE PARAIPABA',
            'MUNICÍPIO DE PEDRA BRANCA',
            'MUNICÍPIO DE PENAFORTE',
            'MUNICÍPIO DE PENTECOSTE',
            'MUNICÍPIO DE PEREIRO',
            'MUNICÍPIO DE PINDORETAMA',
            'MUNICÍPIO DE PIRES FERREIRA',
            'MUNICÍPIO DE POTIRETAMA',
            'MUNICÍPIO DE QUITERIANÓPOLIS',
            'MUNICÍPIO DE QUIXADÁ',
            'MUNICÍPIO DE QUIXELÔ',
            'MUNICÍPIO DE QUIXERAMOBIM',
            'MUNICÍPIO DE RERIUTABA',
            'MUNICÍPIO DE RUSSAS',
            'MUNICÍPIO DE SABOEIRO',
            'MUNICÍPIO DE SÃO BENEDITO',
            'MUNICÍPIO DE SÃO GONÇALO DO AMARANTE',
            'MUNICÍPIO DE SANTANA DO ACARAÚ',
            'MUNICÍPIO DE SANTANA DO CARIRI',
            'MUNICÍPIO DE SANTA QUITÉRIA',
            'MUNICÍPIO DE SENADOR POMPEU',
            'SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO DE SOBRA',
            'MUNICÍPIO DE SOBRAL',
            'MUNICÍPIO DE SOLONÓPOLE',
            'MUNICÍPIO DE TABULEIRO DO NORTE',
            'MUNICÍPIO DE TAMBORIL',
            'MUNICÍPIO DE TAUÁ',
            'MUNICÍPIO DE TIANGUA',
            'MUNICÍPIO DE TRAIRI',
            'MUNICÍPIO DE URUBURETAMA',
            'MUNICÍPIO DE UBAJARA',
            'MUNICÍPIO DE URUOCA',
            'MUNICÍPIO DE VARJOTA',
            'FUNDAÇÃO UNIVERSIDADE DO AMAZONAS',
        ],
        ESPECIAL: [
            'ESTADO DO CEARÁ',
            'MUNICÍPIO DE FORTALEZA',
            'MUNICÍPIO DE ACARAPE',
            'MUNICÍPIO DE ALCÂNTARAS',
            'MUNICÍPIO DE ALTO SANTO',
            'MUNICÍPIO DE BAIXIO',
            'MUNICÍPIO DE BARRO',
            'MUNICÍPIO DE BATURITÉ',
            'MUNICÍPIO DE CANINDÉ',
            'MUNICÍPIO DE COREAU',
            'MUNICÍPIO DE CROATÁ',
            'MUNICÍPIO DE GRANJA',
            'MUNICÍPIO DE GRANJEIRO',
            'MUNICÍPIO DE IBIAPINA',
            'MUNICÍPIO DE INDEPENDÊNCIA',
            'MUNICÍPIO DE LIMOEIRO DO NORTE',
            'MUNICÍPIO DE MARTINÓPOLE',
            'MUNICÍPIO DE MILAGRES',
            'MUNICÍPIO DE MISSÃO VELHA',
            'MUNICÍPIO DE PACUJÁ',
            'MUNICÍPIO DE PARAMOTI',
            'MUNICÍPIO DE PORANGA',
            'MUNICÍPIO DE QUIXERE',
            'MUNICÍPIO DE SÃO LUIS DO CURU',
            'MUNICÍPIO DE SENADOR SÁ',
            'MUNICÍPIO DE VARZEA ALEGRE',
        ],
    },
    DF: {
        COMUM: [
            'MUNICÍPIO DE ARRAIAS',
            'MUNICÍPIO DE CURAÇÁ',
            'MUNICÍPIO DE FORMOSA',
            'MUNICÍPIO DE NOVA SOURÉ',
            'MUNICÍPIO DE PLANALTINA',
            'MUNICÍPIO DE SAMBAÍBA',
            'MUNICÍPIO DE SÃO GERALDO DO ARAGUAIA',
            'MUNICÍPIO DE SÃO JOSÉ DOS BASÍLIOS',
            'MUNICÍPIO DE SERRA DO RAMALHO',
            'MUNICÍPIO DE VALPARAÍSO DE GOIÁS',
        ],
        ESPECIAL: ['DISTRITO FEDERAL'],
    },
    ES: {
        COMUM: [
            'CEASA - CENTRAIS DE ABASTECIMENTO DO ESPIRITO SANTO SA',
            'DEPARTAMENTO DE ESTRADAS DE RODAGEM-D.E.R.',
            'DETRAN- DEPARTAMENTO ESTADUAL DE TRANSITO',
            'FACULDADE DE MUSICA DO ESPIRITO SANTO - FAMES',
            'IASES - INSTITUTO DE ATENDIMENTO SÓCIOEDUCATIVO DO ESPIRITO SANTO',
            'IDAF - INST. DEF. AGROP. FLORESTAL DO E.S.',
            'IMPRENSA OFICIAL DO ESTADO',
            'INST. DE PREV. E ASSIST. SERVIDORES DO MUNICÍPIO DE VITÓRIA',
            'INSTITUTO DE PREV. DO MUNICÍPIO DE VILA VELHA - IPASVV',
            'INSTITUTO DE PREVIDENCIA DOS SERVIDORES PUBLICOS DO MUNICIPIO DE ITAPEMIRIM-ES',
            'INSTITUTO DE PREVIDENCIA DOS SERVIDORES PUBLICOS MUNICIPAIS DE MIMOSO DO SUL - IPREVMIMOSO',
            'INSTITUTO JONES DOS SANTOS NEVES',
            'MUNICÍPIO DE AFONSO CLAUDIO',
            'MUNICÍPIO DE ÁGUIA BRANCA',
            'MUNICÍPIO DE ANCHIETA',
            'MUNICÍPIO DE ARACRUZ',
            'MUNICÍPIO DE ATILIO VIVACQUA',
            'MUNICÍPIO DE BREJETUBA',
            'MUNICÍPIO DE CACHOEIRO DE ITAPEMIRIM',
            'MUNICÍPIO DE CARIACICA',
            'MUNICÍPIO DE COLATINA',
            'MUNICÍPIO DE CONCEIÇÃO DA BARRA',
            'MUNICÍPIO DE DIVINO DE SÃO LOURENÇO',
            'MUNICÍPIO DE DORES DO RIO PRETO',
            'MUNICÍPIO DE FUNDÃO',
            'MUNICÍPIO DE IBATIBA',
            'MUNICÍPIO DE IBITIRAMA',
            'MUNICÍPIO DE IRUPI',
            'MUNICÍPIO DE JAGUARÉ',
            'MUNICÍPIO DE JERÔNIMO MONTEIRO',
            'MUNICÍPIO DE LARANJA DA TERRA',
            'MUNICÍPIO DE LINHARES',
            'MUNICÍPIO DE MARATAÍZES',
            'MUNICÍPIO DE MARECHAL FLORIANO',
            'MUNICÍPIO DE MARILÂNDIA',
            'MUNICÍPIO DE MIMOSO DO SUL',
            'MUNICÍPIO DE MUNIZ FREIRE',
            'MUNICÍPIO DE PANCAS',
            'MUNICÍPIO DE PEDRO CANÁRIO',
            'MUNICÍPIO DE PINHEIROS',
            'MUNICÍPIO DE PIÚMA',
            'MUNICÍPIO DE SÃO MATEUS',
            'MUNICÍPIO DE SERRA',
            'MUNICÍPIO DE VARGEM ALTA',
            'MUNICÍPIO DE VILA VELHA',
            'SANEAR SERV COLATINENSE DE MEIO AMB E SANEAMENTO AMBIENTAL',
        ],
        ESPECIAL: [
            'Município de Alto Rio Novo',
            'Município de Guarapari',
            'Município de Muqui',
            'Município de Viana',
        ],
    },
    FEDERAL: {
        COMUM: [
            'AGENCIA ESPACIAL BRASILEIRA',
            'AGENCIA NACIONAL DE AGUAS E SANEAMENTO BASICO',
            'AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL - ANAC',
            'AGENCIA NACIONAL DE ENERGIA ELETRICA',
            'AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL',
            'AGENCIA NACIONAL DE MINERACAO',
            'AGENCIA NACIONAL DE MINERAÇÃO - ANM',
            'AGÊNCIA NACIONAL DE MINERAÇÃO - ANM',
            'AGENCIA NACIONAL DE PETROLEO - ANP',
            'AGENCIA NACIONAL DE SAUDE SUPLEMENTAR',
            'AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR - ANS',
            'AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR - ANSS',
            'AGENCIA NACIONAL DE SAUDE SUPLEMENTAR ANS',
            'AGENCIA NACIONAL DE TELECOMUNICACOES',
            'AGÊNCIA NACIONAL DE TELECOMUNICAÇÕES - ANATEL',
            'AGENCIA NACIONAL DE TRANSPORTE TERRESTRES',
            'AGÊNCIA NACIONAL DE TRANSPORTES AQUAVIÁRIOS - ANTAQ',
            'AGENCIA NACIONAL DE TRANSPORTES TERRESTRES - ANTT',
            'AGÊNCIA NACIONAL DE TRANSPORTES TERRESTRES - ANTT',
            'AGENCIA NACIONAL DE VIGILANCIA SANITARIA',
            'AGENCIA NACIONAL DE VIGILANCIA SANITARIA - ANVISA',
            'AGÊNCIA NACIONAL DE VIGILÂNCIA SANITÁRIA - ANVISA',
            'AGENCIA NACIONAL DO PETROLEO GAS NATURAL BIOCOMBUSTIVEIS (32265)',
            'AGÊNCIA NACIONAL DO PETRÓLEO, GÁS NATURAL E BIOCOMBUSTÍVEIS - ANP',
            'ANAC - AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL',
            'ANEEL - AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA',
            'ANM - AGENCIA NACIONAL DE MINERACAO',
            'ANP - AGÊNCIA NACIONAL DO PETRÓLEO',
            'ANS - AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR',
            'ANVISA - AGÊNCIA NACIONAL DE VIGILÂNCIA SANITÁRIA',
            'BACEN - BANCO CENTRAL DO BRASIL',
            'BANCO CENTRAL DO BRASIL',
            'BANCO CENTRAL DO BRASIL - BACEN',
            'BANCO CENTRAL DO BRASIL BACEN',
            'CAIXA DE CONSTRUÇÃO DE CASAS P PESSOAL DA MARINHA - CCCPM',
            'CENTRO FEDERAL DE EDUCACAO TECNOLOGICA CELSO SUCKOW DA FONSECA',
            'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA CSF - CEFET',
            'CENTRO FEDERAL DE EDUCACAO TECNOLOGICA DE MINAS GERAIS',
            'CENTRO FEDERAL DE EDUCACAO TECNOLOGICA DE MINAS GERAIS CEFET/MG',
            'CNEN - COMISSÃO NACIONAL DE ENERGIA NUCLEAR',
            'CODEVASF - COMPANHIA DE DESENVOLVIMENTO DOS VALES DO SÃO FRANCISCO E DO PARNAÍBA',
            'COLEGIO PEDRO II',
            'COMISSAO DE VALORES MOBILIARIOS - CVM',
            'COMISSAO NACIONAL DE ENERGIA NUCLEAR',
            'COMISSAO NACIONAL DE ENERGIA NUCLEAR - CNEN',
            'COMISSÃO NACIONAL DE ENERGIA NUCLEAR - CNEN',
            'COMISSAO NACIONAL DE ENERGIA NUCLEAR CNEN',
            'COMPANHIA BRASILEIRA DE TRENS URBANOS',
            'COMPANHIA BRASILEIRA DE TRENS URBANOS CBTU',
            'COMPANHIA DE DESENVOLVIMENTO DOS VALES DO SAO FRANCISCO E DO PARNAIBA',
            'CONSELHO ADMINISTRATIVO DE DEFESA ECONOMICA',
            'CONSELHO NACIONAL DE DESENVOLVIMENTO CIENTIFICO TECNOLOGICO - CNPQ',
            'CVM - COMISSÃO DE VALORES MOBILIÁRIOS',
            'DEPARTAMENTO NACIONAL DE INFRA-ESTRUTURA DE TRANSPORTES',
            'DEPARTAMENTO NACIONAL DE INFRAESTRUTURA DE TRANSPORTES DNIT',
            'DEPARTAMENTO NACIONAL DE OBRAS CONTRA AS SECAS',
            'DEPARTAMENTO NACIONAL DE OBRAS CONTRA AS SECAS - DNOCS',
            'DEPTO NACIONAL DE INFRA-ESTRUTURA DE TRANSPORTES - DNIT',
            'DNIT - DEPARTAMENTO NACIONAL DE INFRA-ESTRUTURA DE TRANSPORTES',
            'DNOCS - DEPARTAMENTO NACIONAL DE OBRAS CONTRA AS SECAS',
            'EMPRESA BRASILEIRA DE CORREIOS E TELÉGRAFOS - ECT',
            'EMPRESA BRASILEIRA DE INFRAESTRUTURA AEROPORTUÁRIA - INFRAERO',
            'EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUÁRIA - INFRAERO',
            'EMPRESA BRASILEIRA DE SERVIÇOS HOSPITALARES - EBSERH',
            'ENCARGOS FINANCEIROS DA UNIÃO - SENTENÇAS JUDICIAIS',
            'FIOCRUZ - FUNDAÇÃO OSWALDO CRUZ',
            'FNDE - FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCAÇÃO',
            'FUB/UNB - FUNDAÇÃO UNIVERSIDADE DE BRASÍLIA',
            'FUNAI - FUNDAÇÃO NACIONAL DO ÍNDIO',
            'FUNASA - FUNDAÇÃO NACIONAL DE SAÚDE',
            'FUNDACAO BIBLIOTECA NACIONAL',
            'FUNDAÇÃO BIBLIOTECA NACIONAL - FBN',
            'FUNDACAO CASA DE RUI BARBOSA',
            'FUNDACAO COORDENACAO DE APERFEICOAMENTO DE PESSOAL DE NIVEL SUPERIOR',
            'FUNDAÇÃO COORDENAÇÃO DE APERFEIÇOAMENTO DE PESSOAL DE NÍVEL SUPERIOR - CAPES',
            'FUNDACAO CULTURAL PALMARES',
            'FUNDACAO INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATISTICA',
            'FUNDACAO INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATISTICA - IBGE',
            'FUNDAÇÃO JORGE DUPRAT FIGUEIREDO DE SEGURANÇA E MEDICINA DO TRABALHO - FUNDACENTRO',
            'FUNDACAO NACIONAL DE ARTES',
            'FUNDACAO NACIONAL DE SAUDE',
            'FUNDAÇÃO NACIONAL DE SAÚDE - FUNASA',
            'FUNDACAO NACIONAL DE SAUDE FUNASA',
            'FUNDACAO NACIONAL DO INDIO',
            'FUNDACAO NACIONAL DO INDIO - FUNAI',
            'FUNDACAO OSORIO',
            'FUNDACAO OSWALDO CRUZ',
            'FUNDACAO UNIVERSIDADE DE BRASILIA',
            'FUNDACAO UNIVERSIDADE DE OURO PRETO ',
            'FUNDACAO UNIVERSIDADE DO AMAZONAS',
            'FUNDACAO UNIVERSIDADE DO RIO DE JANEIRO',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DA GRANDE DOURADOS - UFGD',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DE CIÊNCIAS DA SAÚDE DE PORTO ALEGRE - UFCSPA',
            'FUNDACAO UNIVERSIDADE FEDERAL DE MATO GROSSO',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DE MATO GROSSO DO SUL',
            'FUNDACAO UNIVERSIDADE FEDERAL DE OURO PRETO',
            'FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DE RONDONIA',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DE SÃO CARLOS',
            'FUNDACAO UNIVERSIDADE FEDERAL DE SAO JOAO DEL REI',
            'FUNDACAO UNIVERSIDADE FEDERAL DE VICOSA',
            'Fundação Universidade Federal do ABC - UFABC ',
            'FUNDACAO UNIVERSIDADE FEDERAL DO ACRE',
            'FUNDACAO UNIVERSIDADE FEDERAL DO MARANHAO',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DO PAMPA - UNIPAMPA',
            'FUNDACAO UNIVERSIDADE FEDERAL DO PIAUI',
            'FUNDAÇÃO UNIVERSIDADE FEDERAL DO RIO GRANDE/RS - UFRG',
            'FUNDACAO UNVERSIDADE FEDERAL DO TOCANTINS',
            'FUNDAJ - FUNDAÇÃO JOAQUIM NABUCO',
            'FUNDO DO REGIME GERAL DA PREVIDENCIA SOCIAL',
            'FUNDO DO REGIME GERAL DA PREVIDÊNCIA SOCIAL',
            'FUNDO NACIONAL DA ASSISTENCIA SOCIAL',
            'FUNDO NACIONAL DE ASSISTENCIA SOCIAL',
            'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
            'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCAÇÃO - FNDE',
            'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCAÇÃO FNDE',
            'FUNDO NACIONAL DE SAÚDE',
            'HOSPITAL DE CLÍNICAS DE PORTO ALEGRE',
            'HOSPITAL NOSSA SENHORA DA CONCEIÇÃO S/A',
            'IBAMA - INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVÁVEIS',
            'IBGE - FUNDAÇÃO INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATÍSTICA',
            'IFET/AL-INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE ALAGOAS',
            'IFET/CE - INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ',
            'IFET/PB - INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DA PARAÍBA',
            'IFET/PE - INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO',
            'IFET/RN - INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO NORTE',
            'IFET/SE - INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE SERGIPE',
            'INCRA - INSTITUTO NACIONAL DE COLONIZAÇÃO E REFORMA AGRÁRIA',
            'Indústria de Material Bélico do Brasil - IMBEL',
            'INSS - INSTITUTO NACIONAL DO SEGURO SOCIAL',
            'INSTITUTO BRAS MEIO AMBIENTE E RECURSOS NATURAIS RENOVAVEIS - IBAMA',
            'INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVAVEIS',
            'INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVÁVEIS - IBAMA',
            'INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVAVEIS IBAMA',
            'INSTITUTO CHICO MENDES CONSERVACAO BIODIVERSIDADE - ICMBIO',
            'INSTITUTO CHICO MENDES DE CONSERVACAO DA BIODIVERSIDADE',
            'INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE - ICMBIO',
            'INSTITUTO CHICO MENDES DE CONSERVACAO DA BIODIVERSIDADE ICMBIO',
            'INSTITUTO DE PESQUISA ECONOMICA APLICADA',
            'INSTITUTO DE PESQUISAS JARDIM BOTÂNICO DO RIO DE JANEIRO',
            'INSTITUTO DO PATRIMONIO HISTORICO E ARTISTICO NACIONAL',
            'INSTITUTO DO PATRIMONIO HISTORICO E ARTISTICO NACIONAL - IPHAN',
            'INSTITUTO DO PATRIMÔNIO HISTÓRICO E ARTÍSTICO NACIONAL - IPHAN',
            'INSTITUTO FEDERAL AMAPA',
            'INSTITUTO FEDERAL BAIANO',
            'INSTITUTO FEDERAL DA BAHIA',
            'INSTITUTO FEDERAL DE BRASILIA',
            'INSTITUTO FEDERAL DE EDUCACAO CIENCIA  E TECNOLOGIA DE MINAS GERAIS IFMG',
            'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO NORTE DE MINAS GERAIS IFNMG',
            'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO SUDESTE DE MINAS GERAIS IFSUDESTE',
            'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO SUL DE MINAS GERAIS IFSULDEMINAS',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA CATARINENSE - IF CATARINENSE',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE BRASÍLIA - IFBRASÍLIA',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE SANTA CATARINA - IF SANTA CATARINA',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO AMAPÁ - IFAMAPÁ',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO PARANÁ - IF PARANÁ',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL - IFRS',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO SERTÃO PERNAMBUCANO - IF SERTÃO PERNAMBUCANO',
            'INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA DO TOCANTINS - IFTOCANTINS',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA FARROUPILHA - IF FARROUPILHA',
            'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA SULRIOGRANDENSE - IF SULRIOGRANDENSE',
            'INSTITUTO FEDERAL DE GOIAS',
            'INSTITUTO FEDERAL DE MINAS GERAIS',
            'INSTITUTO FEDERAL DE RONDONIA',
            'INSTITUTO FEDERAL DE SÃO PAULO',
            'INSTITUTO FEDERAL DO ACRE',
            'INSTITUTO FEDERAL DO AMAZONAS',
            'INSTITUTO FEDERAL DO ESPÍRITO SANTO',
            'INSTITUTO FEDERAL DO MARANHAO',
            'INSTITUTO FEDERAL DO MATO GROSSO',
            'INSTITUTO FEDERAL DO MATO GROSSO DO SUL',
            'INSTITUTO FEDERAL DO NORTE DE MINAS GERAIS',
            'INSTITUTO FEDERAL DO PARA',
            'INSTITUTO FEDERAL DO PIAUI',
            'INSTITUTO FEDERAL DO RIO DE JANEIRO',
            'INSTITUTO FEDERAL DO SERTAO PERNAMBUCANO',
            'INSTITUTO FEDERAL DO SUDESTE DE MINAS GERAIS',
            'INSTITUTO FEDERAL DO SUL DE MINAS GERAIS',
            'INSTITUTO FEDERAL DO TRIANGULO MINEIRO',
            'INSTITUTO FEDERAL DO TRIANGULO MINEIRO IFTM',
            'INSTITUTO FEDERAL FLUMINENSE',
            'INSTITUTO FEDERAL GOIANO',
            'INSTITUTO NACIONAL DA PROPRIEDADE INDUSTRIAL - INPI',
            'INSTITUTO NACIONAL DE COLONIZACAO E REFORMA AGRARIA',
            'INSTITUTO NACIONAL DE COLONIZACAO E REFORMA AGRARIA - INCRA',
            'INSTITUTO NACIONAL DE ESTUDOS E PESQUISAS EDUCACIONAIS ANISIO TEIXEIRA',
            'INSTITUTO NACIONAL DE METROLOGIA QUALIDADE E TECNOLOGIA INMETRO',
            'INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS',
            'IPHAN - INSTITUTO DO PATRIMÔNIO HISTÓRICO E ARTÍSTICO NACIONAL',
            'SUDENE - SUPERINTENDÊNCIA DO DESENVOLVIMENTO DO NORDESTE',
            'SUPERINTENDENCIA DA ZONA FRANCA DE MANAUS',
            'SUPERINTENDENCIA DE SEGUROS PRIVADOS',
            'SUPERINTENDÊNCIA DE SEGUROS PRIVADOS - SUSEP',
            'SUPERINTENDENCIA DO DESENVOLVIMENTO DA AMAZONIA',
            'SUPERINTENDENCIA NACIONAL DE PREVIDENCIA COMPLEMENTAR',
            'UFAL - UNIVERSIDADE FEDERAL DE ALAGOAS',
            'UFC - UNIVERSIDADE FEDERAL DO CEARÁ',
            'UFCG - UNIVERSIDADE FEDERAL DE CAMPINA GRANDE (PARAÍBA)',
            'UFERSA - UNIVERSIDADE FEDERAL RURAL DO SEMI-ÁRIDO',
            'UFPB - UNIVERSIDADE FEDERAL DA PARAÍBA',
            'UFPE - UNIVERSIDADE FEDERAL DE PERNAMBUCO',
            'UFRN - UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE',
            'UFRPE - UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO',
            'UFS - UNIVERSIDADE FEDERAL DE SERGIPE',
            'UNIÃO FEDERAL',
            'UNIVASF - FUNDAÇÃO UNIVERSIDADE FEDERAL  DO VALE DO SÃO FRANCISCO',
            'UNIVERSIDADE DA INTEGRAÇÃO INTERNACIONAL DA LUSOFONIA AFRO-BRASILEIRA - UNILAB',
            'UNIVERSIDADE FEDERAL DA BAHIA',
            'UNIVERSIDADE FEDERAL DA FRONTEIRA SUL - UFFS',
            'UNIVERSIDADE FEDERAL DA INTEGRAÇÃO LATINO AMERICANA - UNILA',
            'UNIVERSIDADE FEDERAL DE ALFENAS',
            'UNIVERSIDADE FEDERAL DE GOIAS',
            'UNIVERSIDADE FEDERAL DE ITAJUBA',
            'UNIVERSIDADE FEDERAL DE JUIZ DE FORA',
            'UNIVERSIDADE FEDERAL DE JUIZ DE FORA UFJF',
            'UNIVERSIDADE FEDERAL DE LAVRAS',
            'UNIVERSIDADE FEDERAL DE LAVRAS UFLA',
            'UNIVERSIDADE FEDERAL DE MINAS GERAIS',
            'UNIVERSIDADE FEDERAL DE MINAS GERAIS UFMG',
            'UNIVERSIDADE FEDERAL DE PELOTAS - UFPEL',
            'UNIVERSIDADE FEDERAL DE RORAIMA',
            'UNIVERSIDADE FEDERAL DE SANTA CATARINA - UFSC',
            'UNIVERSIDADE FEDERAL DE SANTA MARIA - UFSM',
            'UNIVERSIDADE FEDERAL DE SAO PAULO',
            'UNIVERSIDADE FEDERAL DE UBERLANDIA',
            'UNIVERSIDADE FEDERAL DE UBERLANDIA UFU',
            'UNIVERSIDADE FEDERAL DE VICOSA UFV',
            'UNIVERSIDADE FEDERAL DO CEARA',
            'UNIVERSIDADE FEDERAL DO ESPIRITO SANTO',
            'UNIVERSIDADE FEDERAL DO MATO GROSSO DO SUL',
            'UNIVERSIDADE FEDERAL DO OESTE DO PARA',
            'UNIVERSIDADE FEDERAL DO PARA',
            'UNIVERSIDADE FEDERAL DO PARANÁ - UFPR',
            'UNIVERSIDADE FEDERAL DO RECONCAVO DA BAHIA',
            'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
            'UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL - UFRGS',
            'UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO',
            'UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO UFTM',
            'UNIVERSIDADE FEDERAL FLUMINENSE',
            'UNIVERSIDADE FEDERAL RURAL DA AMAZONIA',
            'UNIVERSIDADE FEDERAL RURAL DO RIO DE JANEIRO',
            'UNIVERSIDADE TECNOLÓGICA FEDERAL DO PARANÁ - UTFPR',
            'VALEC ENGENHARIA CONSTRUCOES E FERROVIAS S/A',
            'VALEC ENGENHARIA CONSTRUCOES E FERROVIAS SA',
            'FAZENDA NACIONAL (UNIÃO FEDERAL)',
        ],
    },
    GO: {
        COMUM: [
            'Abadiânia',
            'Adelândia',
            'AGENCIA DA GUARDA CIVIL METROPOLITANA DE GOIANIA',
            'AGÊNCIA DE SANEAMENTO DE SENADOR CANEDO - SANESC',
            'AGÊNCIA MUNICIPAL DO MEIO AMBIENTE - AMMA',
            'Água Fria de Goiás',
            'Águas Lindas',
            'Aloândia',
            'Alto Horizonte',
            'Alvorada do Norte',
            'Americano do Brasil',
            'Amorinópolis',
            'Anhanguera',
            'Aparecida do Rio Doce',
            'Aporé',
            'Araçu',
            'Aragarças',
            'Aragoiânia',
            'Araguapaz',
            'Aruanã',
            'Aurilândia',
            'Baliza',
            'Barro Alto',
            'Bela Vista',
            'Bom Jardim de Goiás',
            'Bonfinópolis',
            'Bonópolis',
            'Britânia',
            'Buriti Alegre',
            'Cabeceiras',
            'Cachoeira Alta',
            'Caçu',
            'Caiapônia',
            'Caldas Novas',
            'Caldazinha',
            'CÂMARA MUNICIPAL DE ARAGOIÂNIA',
            'Campinaçu',
            'Castelândia',
            'Catalão',
            'Caturaí',
            'Ceres',
            'Cezarina',
            'Cocalzinho',
            'Colinas do Sul',
            'COMPANHIA DE URBANIZACAO DE GOIANIA - COMURG',
            'Corrego do Ouro',
            'Corumbá de Goiás',
            'Corumbaíba',
            'Cristalina',
            'Cristianópolis',
            'Crixás',
            'Cromínia',
            'Cumari',
            'Davinópolis',
            'Diorama',
            'Divinópolis de Goiás',
            'Doverlândia',
            'Edealina',
            'Edéia',
            'Estrela do Norte',
            'FESURV',
            'Firminópolis',
            'Flores de Goiás',
            'Formosa',
            'FUNDACAO INTEGRADA MUNICIPAL DE ENSINO SUPERIOR DE MINEIROS - FIMES',
            'FUNDO DE PREVIDÊNCIA DE CRISTALINA - FUNCRISTAL',
            'FUNDO DE PREVIDÊNCIA DOS SERVIDORES DE FIRMINÓPOLIS - FUNPREV',
            'FUNDO DE PREVIDENCIA O MUNICIPIO DE CALDAS NOVAS',
            'FUNDO DE PREVIDENCIA SOCIAL DE TAQUARAL DE GOIAS',
            'FUNDO DE PREVIDÊNCIA SOCIAL DO MUNICÍPIO DE PIRES DO RIO',
            'FUNDO MUNICIPAL DE EDUCAÇÃO DO MUNICIPIO DE CALDAS NOVAS',
            'FUNDO MUNICIPAL DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE MONTES CLAROS DE GOIÁS',
            'FUNDO MUNICIPAL DE PREVIDENCIA SOCIAL DOS SERVIDORES DE BARRO ALTO - BARRO ALTO-PREVI',
            'FUNDO MUNICIPAL DE PREVIDÊNCIA SOCIAL DOS SERVIDORES DE BELA VISTA DE GOIÁS - PREVIBEL',
            'FUNDO MUNICIPAL DE PREVIDÊNCIA SOCIAL DOS SERVIDORES DE CAÇU',
            'FUNDO MUNICIPAL DE PREVIDENCIA SOCIAL DOS SERVIDORES DO MUNICIPIO DE ITARUMA - ITARUMA - PREVI',
            'FUNDO MUNICIPAL DE PREVIDÊNCIA SOCIAL DOS SERVIDORES DO MUNICÍPIO DE MOZARLÂNDIA - MOZAR PREVI',
            'FUNDO MUNICIPAL DE PREVIDENCIA SOCIAL DOS SERVIDORES DO MUNICIPIO DE NOVO BRASIL',
            'FUNDO MUNICIPAL DE PROTEÇÃO E DEFESA DO CONSUMIDOR DE RIO VERDE',
            'FUNDO MUNICIPAL DE SAÚDE DE CRISTALINA',
            'FUNDO MUNICIPAL DE SAÚDE DE JARAGUÁ/GO',
            'FUNDO MUNICIPAL DE SAÚDE DE SANCLERLÂNDIA',
            'FUNDO MUNICIPAL DE SAÚDE DE SANTA CRUZ DE GOIÁS',
            'FUNDO MUNICIPAL DE SAÚDE DE SIMOLÂNDIA - FMS',
            'FUNDO MUNICIPAL DE SAÚDE DO MUNICÍPIO DE PIRES DO RIO',
            'FUNDO PREVIDÊNCIÁRIO DO MUNÍCIPIO DE SANTA ISABEL',
            'FUNDO SOCIAL DE SANTA FÉ DE GOIÁS - FUNPASA',
            'FUNPRES (INHUMAS)',
            'FUNPREVAR - FUNDO DE PREVIDÊNCIA SOCIAL DO MUNICÍPIO DE VARJÃO',
            'FUNPREVI FUNDO DE PREVIDENCIA SOCIAL DO MUNICIPIO DE GOIANÉSIA',
            'Goianápolis',
            'Goiandira',
            'Goianésia',
            'Goiânia',
            'Goianira',
            'Gouvelândia',
            'Guapó',
            'Guarani de Goiás',
            'Guarinos',
            'Heitoraí',
            'Hidrolândia',
            'Hidrolina',
            'IMAS - INSTITUTO DE ASSISTÊNCIA A SAÚDE E SOCIAL DOS SERVIDORES MUNICIPAIS DE GOIÂNIA',
            'Inaciolândia',
            'Indiara',
            'Inhumas',
            'INPASC - INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DE SANTA CRUZ',
            'INSTITUTO DE ASSISTÊNCIA A SAÚDE DO SERVIDOR PÚBLICO DE SENADOR CANEDO - IAMESC',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO MUNICÍPIO DE MONTIVIDIU - PREVIM',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DE SÃO MIGUEL DO ARAGUAIA - ARAGUAIA PREV',
            'INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE TRINDADE - TRINDADE PREV',
            'INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DOS SERVIDORES DO MUNICÍPIO DE LUZIÂNIA - IPASLUZ',
            'INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DOS SERVIDORES PÚBLICOS DE VALPARAÍSO DE GOIÁS - IPASVAL',
            'INSTITUTO DE PREVIDENCIA MUNICIPAL DE ITAUÇU - IPREMI',
            'INSTITUTO DE PREVIDÊNCIA SOCIAL DE MUNICÍPIO DE HEITORAI - IPASHE',
            'INSTITUTO DE PREVIDÊNCIA SOCIAL DO MUNICÍPIO DE PADRE BERNARDO - PABPREV',
            'INSTITUTO DE PREVIDÊNCIA SOCIAL DO MUNICÍPIO DE SÃO MIGUEL DO PASSA QUATRO',
            'INSTITUTO DE PREVIDÊNCIA SOCIAL DOS SERVIDORES PÚBLICOS DO MUNICÍPIO DE CORUMBAÍBA',
            'INSTITUTO MUNICIPAL DE PREVIDÊNCIA E ASSISTÊNCIA DOS SERVIDORES DE PIRANHAS - IPASPI',
            'INSTITUTO MUNÍCIPAL DE PREVIDÊNCIA SOCIAL DOS SERVIDORES DO MUNICÍPIO DE MINEIROS - MINEIROSPREVI',
            'IPARV - INSTITUTO DE PREVIDENCIA E ASSITENCIA DOS SERVIDORES MUNICIPAIS DE RIO VERDE',
            'IPASI - INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA SOCIAL DOS SERVIDORES DE IPORÁ',
            'IPASI - INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA SOCIAL DOS SERVIDORES DE ITAJÁ',
            'Iporá',
            'IPSM - INSTITUTO DE PREVIDENCIA DOS SERVIDORES MUNICIPAIS DE GOIANIA',
            'Itaguaru',
            'Itagurari',
            'Itajá',
            'Itapaci',
            'Itapirapuã',
            'Itarumã',
            'Itauçu',
            'Jandaia',
            'Jaraguá',
            'Jataí',
            'JATAIPREV',
            'Joviânia',
            'Juapaci',
            'Jussara',
            'Lagoa Santa',
            'Luziânia',
            'Mairipotaba',
            'Mambaí',
            'Marzagão',
            'Matrinchã',
            'Maurilândia',
            'Mimoso de Goiás',
            'Mineiros',
            'Moiporá',
            'Monte Alegre de Goiás',
            'Montes Claros de Goiás',
            'Montevidiu do Norte',
            'Montividiu',
            'Morrinhos',
            'Morro Agudo de Goiás',
            'Mozarlândia',
            'Mundo Novo',
            'MUNICÍPIO DE ARGIRITA',
            'Mutunópolis',
            'Nazário',
            'Neropólis',
            'Niquelândia',
            'Nova América',
            'Nova Aurora',
            'Nova Crixás',
            'Nova Roma',
            'Nova Veneza',
            'Novo Brasil',
            'Novo Gama',
            'Novo Planalto',
            'Ouro Verde de Goiás',
            'Ouvidor',
            'Palestina de Goiás',
            'Palmelo',
            'Panamá',
            'Paranaiguara',
            'Petrolina de Goiás',
            'Piracanjuba',
            'Piranhas',
            'Pirenópolis',
            'Pires do Rio',
            'Pontalina',
            'Porteirão',
            'Portelândia',
            'PREV ABADIA',
            'PREV CERES - INSTITUTO DE PREVIDÊNCIA SOCIAL DE CERES',
            'PREVJUS - INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO MUNICÍPIO DE JUSSARA',
            'Quirinópolis',
            'QUIRINÓPOLIS PREVIDÊNCIA - QUIPREV',
            'Rianápolis',
            'Rio Quente',
            'Rio Verde',
            'SAAE (ABADIÂNIA)',
            'SAAE (MINEIROS)',
            'Sanclerlândia',
            'Santa Cruz',
            'Santa Fé de Goiás',
            'Santa Helena',
            'Santa Isabel',
            'Santa Rita do Araguaia',
            'Santa Terezinha de Goiás',
            'Santo Antônio da Barra',
            'Santo Antônio de Goiás',
            'São Domingos',
            'São Francisco de Goiás',
            'São João da Paraúna',
            "São João D'Aliança",
            'São Luis de Montes Belos',
            'São Luiz do Norte',
            'São Miguel do Araguaia',
            'São Miguel do Passa Quatro',
            'São Patrício',
            'SECRETARIA MUNICIPAL DE EDUCAÇÃO E CULTURA DA COMARCA DE CRISTALINA - GO',
            'Senador Canedo',
            'SENAPREV - INSTITUTO DE PREVIDÊNCIA DO SERVIDOR PÚBLICO DE SENADOR CANEDO',
            'Serranópolis',
            'Silvânia',
            "Sítio D'abadia",
            'Superintendência Municipal de Água e Esgoto de Catalão - SAE',
            'Taquaral de Goiás',
            'Terezinha de Goiás',
            'Terezópolis',
            'Três Ranchos',
            'Trindade',
            'Trombas',
            'Turvânia',
            'Uirapuru',
            'Urutaí',
            'Valparaíso',
            'Varjão',
            'Vianópolis',
            'Vicentinópolis',
            'Vila Boa',
            'Vila Propício',
        ],
        ESPECIAL: [
            'Acreúna',
            'Alexânia',
            'Anápolis',
            'Anicuns',
            'Aparecida de Goiânia',
            'Bom Jesus',
            'Cachoeira Dourada',
            'Campinorte',
            'Campo Alegre de Goiás',
            'Campos Belos',
            'Campos Verdes',
            'Carmo do Rio Verde',
            'Cavalcante',
            'Cidade Ocidental',
            'ESTADO DE GOIÁS',
            'Faina',
            'Fazenda Nova',
            'Formoso',
            'Goiás',
            'Goiatuba',
            'Iaciara',
            'Ipameri',
            'Israelândia',
            'Itaberaí',
            'Itapuranga',
            'Itumbiara',
            'Ivolândia',
            'Leopoldo de Bulhões',
            'Mara Rosa',
            'Minaçu',
            'Mossamedes',
            'Nova Glória',
            'Orizona',
            'Padre Bernardo',
            'Palmeiras de Goiás',
            'Paraúna',
            'Pilar de Goiás',
            'Planaltina',
            'Porangatu',
            'Posse',
            'Rialma',
            'Rubiataba',
            'Santa Rosa',
            'Santo Antônio do Descoberto',
            'São Simão',
            'Turvelândia',
            'Uruaçu',
        ],
    },
};
