export const ENTES_RJ_EXCEPCIONADOS = [
    "ESTADO DO RIO DE JANEIRO",
    "Instituto de Previdência do Estado do Rio de Janeiro - IPERJ",
    "Instituto Estadual do Ambiente - INEA",
    "Faculdade de Educação Tecnológica do Estado do Rio de Janeiro - FAETEC",
    "Universidade do Estado do Rio de Janeiro - UERJ",
    "RIOPREVIDÊNCIA",
    "Departamento Estadual de Trânsito - DETRAN- RJ",
    "Universidade Estadual do Norte Fluminense Darcy Ribeiro - UENF",
    "Centro de Tecnologia da Informação e Comunicação do Estado do Rio de Janeiro - PRODERJ",
    "Superintendência de Desportos do Estado do Rio de Janeiro - SUDERJ",
    "Instituto de Assistência dos Servidores do Estado do Rio de Janeiro - IASERJ",
    "Fundação para a Infância e Adolescência - FIARJ",
    "Junta Comercial do Estado do Rio de Janeiro - JUCERJA",
    "Instituto Estadual de Florestas - IEF",
    "FUNDAÇÃO LEÃO XIII",
    "Fundação Carlos Chagas Filho - FAPERJ",
    "Universidade do Estado do Rio de Janeiro campus Zona Oeste - UEZO",
    "CEHAB - Companhia Estadual de Habitação do Rio de Janeiro",
    "Instituto de Pesos e Medidas do Rio de Janeiro - IPEM",
    "Empresa de Assistência Técnica e Extensão Rural do Estado do Rio de Janeiro - EMATER",
    "Empresa de Obras Públicas do Estado do Rio de Janeiro – EMOP",
    "FUNDERJ - FUNDAÇÃO DEPARTAMENTO DE ESTRADAS DE RODAGEM - DER RJ",
    "CENTRAL - CIA. ESTADUAL DE TRANSPORTES E LOGÍSTICA",
    "COMPANHIA FLUMINENSE DE TRENS URBANOS - FLUMITRENS",
    "EMOP - EMPRESA DE OBRAS PÚBLICAS DO EST. DO RJ",
    "LOTERJ - LOTERIA DO ESTADO DO RJ",
    "FMIS - FUNDAÇÃO MUSEU DA IMAGEM E DO SOM",
    "DETRO - DEPARTAMENTO DE TRANSPORTES RODOVIÁRIOS",
    "Instituto de Previdência da Assembleia Legislativa do Estado do Rio de Janeiro - IPALERJ",
    "FUNDAÇÃO ESCOLA DO SERVIÇO PÚBLICO - FESP",
    "COMPANHIA DE TRANSPORTES SOBRE TRILHOS DO ESTADO DO RIO DE JANEIRO - RIOTRILHOS",
    "FUNDAÇÃO DE APOIO A ESCOLA TÉCNICA DO EST. RIO DE JANEIRO",
    "Departamento de Transportes Rodoviários do Estado do Rio de Janeiro - Detro-RJ",
    "Fundação Centro de Ciências e Educação Superior a Distância do Estado do Rio de Janeiro – Fundação CECIERJ",
    "DATA RIO",
    "Empresa de Pesquisa Agropecuária do Estado do Rio de Janeiro - PESAGRO",
    "Fundação Saúde - FSERJ",
    "CUIDAR",
    "Fundação Departamento de Estradas de Rodagem - FUNDERJ",
    "FUNDAÇÃO TEATRO MUNICIPAL DO R.J.",
    "FUNDAÇÃO ESTADUAL DO NORTE FLUMINENSE - FENORTE",
    "FUNDAÇÃO CENTRO DE CIÊNCIA E EDUCAÇÃO SUPERIOR DO ESTADO DO RIO DE JANEIRO - CECIERJ",
    "FUNDAÇÃO DE AMPARO A PESQUISA DO E.R.J.",
    "Fundação para a Infância e Adolescência - FIA",
    "Museu da Imagem e do Som do Rio de Janeiro - MIS",
    "FUNDAÇÃO TEATRO MUNICIPAL",
    "SERLA - FUNDAÇÃO EST. DE RIOS E LAGOAS",
    "FUNDAÇÃO DE APOIO A ESCOLA PÚBLICA - FAEP",
    "Companhia de Transportes Coletivos do Rio de Janeiro - CTC",
    "RIOSAUDE",
    "INSTITUTO ESTADUAL DE TERRAS E CARTOGRAFIA - ITERJ",
    "AGÊNCIA REGULADORA DE ENERGIA E SANEAMENTO BÁSICO DO ESTADO DO RIO DE JANEIRO - AGENERSA",
    "FAPERJ - Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do Rio de Janeiro",
    "INSTITUTO DE ASSISTÊNCIA DOS SERVIDORES DO ESTADO DO RIO DE JANEIRO",
    "AUTARQUIA DE PROTEÇÃO E DEFESA DO CONSUMIDOR DO ESTADO DO RJ",
    "Companhia Estadual de Águas e Esgotos do Rio de Janeiro - CEDAE",
    "COMPANHIA DE TRANSPORTES COLETIVOS CTC"
]

export const regimeEspecialExceptions = [
    'ESTADO DE PERNAMBUCO',
    'FUNAPE - Fundação de Aposentadorias e Pensões do Estado de Pernambuco',
    'FUNAFIN - Fundo Financeiro de Aposentadorias e Pensões dos Servidores do Estado de Pernambuco',
    'INSTITUTO DE RECURSOS HUMANOS DE PERNAMBUCO IRH PE'
];

export const entesComTaxaPrevidenciariaPredefinida = ['ESTADO DE GOIÁS', ...regimeEspecialExceptions];
