export const imgPaths: Record<string, string> = {
  TRF1: "/images/tribunais/card_TRF1.webp",
  TRF2: "/images/tribunais/card_TRF2.webp",
  TRF3: "/images/tribunais/card_TRF3.webp",
  TRF4: "/images/tribunais/card_TRF4.webp",
  TRF5: "/images/tribunais/card_TRF5.webp",
  TRF6: "/images/tribunais/card_TRF6.webp",
  STF: "/images/tribunais/card_STF.webp",
  STJ: "/images/tribunais/card_STJ.webp",
  TST: "/images/tribunais/card_TST.webp",
  TSE: "/images/tribunais/card_TSE.webp",
  STM: "/images/tribunais/card_STM.webp",
  TJAC: "/images/tribunais/card_TJAC.webp",
  TJAL: "/images/tribunais/card_TJAL.webp",
  TJAP: "/images/tribunais/card_TJAP.webp",
  TJAM: "/images/tribunais/card_TJAM.webp",
  TJBA: "/images/tribunais/card_TJBA.webp",
  TJCE: "/images/tribunais/card_TJCE.webp",
  TJDFT: "/images/tribunais/card_TJDFT.webp",
  TJES: "/images/tribunais/card_TJES.webp",
  TJGO: "/images/tribunais/card_TJGO.webp",
  TJMA: "/images/tribunais/card_TJMA.webp",
  TJMT: "/images/tribunais/card_TJMT.webp",
  TJMS: "/images/tribunais/card_TJMS.webp",
  TJMG: "/images/tribunais/card_TJMG.webp",
  TJPA: "/images/tribunais/card_TJPA.webp",
  TJPB: "/images/tribunais/card_TJPB.webp",
  TJPE: "/images/tribunais/card_TJPE.webp",
  TJPI: "/images/tribunais/card_TJPI.webp",
  TJPR: "/images/tribunais/card_TJPR.webp",
  TJRJ: "/images/tribunais/card_TJRJ.webp",
  TJRN: "/images/tribunais/card_TJRN.webp",
  TJRO: "/images/tribunais/card_TJRO.webp",
  TJRR: "/images/tribunais/card_TJRR.webp",
  TJRS: "/images/tribunais/card_TJRS.webp",
  TJSC: "/images/tribunais/card_TJSC.webp",
  TJSE: "/images/tribunais/card_TJSE.webp",
  TJSP: "/images/tribunais/card_TJSP.webp",
  TJTO: "/images/tribunais/card_TJTO.webp",
  TRT1: "/images/tribunais/card_TRT1.webp",
  TRT2: "/images/tribunais/card_TRT2.webp",
  TRT3: "/images/tribunais/card_TRT3.webp",
  TRT4: "/images/tribunais/card_TRT4.webp",
  TRT5: "/images/tribunais/card_TRT5.webp",
  TRT6: "/images/tribunais/card_TRT6.webp",
  TRT7: "/images/tribunais/card_TRT7.webp",
  TRT8: "/images/tribunais/card_TRT8.webp",
  TRT10: "/images/tribunais/card_TRT10.webp",
  TRT11: "/images/tribunais/card_TRT11.webp",
  TRT12: "/images/tribunais/card_TRT12.webp",
  TRT13: "/images/tribunais/card_TRT13.webp",
  TRT14: "/images/tribunais/card_TRT14.webp",
  TRT15: "/images/tribunais/card_TRT15.webp",
  TRT16: "/images/tribunais/card_TRT16.webp",
  TRT17: "/images/tribunais/card_TRT17.webp",
  TRT18: "/images/tribunais/card_TRT18.webp",
  TRT19: "/images/tribunais/card_TRT19.webp",
  TRT20: "/images/tribunais/card_TRT20.webp",
  TRT21: "/images/tribunais/card_TRT21.webp",
  TRT22: "/images/tribunais/card_TRT22.webp",
  TRT23: "/images/tribunais/card_TRT23.webp",
  TRT24: "/images/tribunais/card_TRT24.webp",
};

export const tribunais = [
  { id: "TRF1", nome: "Tribunal Regional Federal - 1ª Região" },
  { id: "TRF2", nome: "Tribunal Regional Federal - 2ª Região" },
  { id: "TRF3", nome: "Tribunal Regional Federal - 3ª Região" },
  { id: "TRF4", nome: "Tribunal Regional Federal - 4ª Região" },
  { id: "TRF5", nome: "Tribunal Regional Federal - 5ª Região" },
  { id: "TRF6", nome: "Tribunal Regional Federal - 6ª Região" },
  { id: "STF", nome: "Supremo Tribunal Federal" },
  { id: "STJ", nome: "Superior Tribunal de Justiça" },
  { id: "TST", nome: "Tribunal Superior do Trabalho" },
  { id: "TSE", nome: "Tribunal Superior Eleitoral" },
  { id: "STM", nome: "Superior Tribunal Militar" },
  { id: "TJAC", nome: "Tribunal de Justiça do Acre" },
  { id: "TJAL", nome: "Tribunal de Justiça de Alagoas" },
  { id: "TJAP", nome: "Tribunal de Justiça do Amapá" },
  { id: "TJAM", nome: "Tribunal de Justiça do Amazonas" },
  { id: "TJBA", nome: "Tribunal de Justiça da Bahia" },
  { id: "TJCE", nome: "Tribunal de Justiça do Ceará" },
  {
    id: "TJDFT",
    nome: "Tribunal de Justiça do Distrito Federal e dos Territórios",
  },
  { id: "TJES", nome: "Tribunal de Justiça do Espírito Santo" },
  { id: "TJGO", nome: "Tribunal de Justiça de Goiás" },
  { id: "TJMA", nome: "Tribunal de Justiça do Maranhão" },
  { id: "TJMT", nome: "Tribunal de Justiça do Mato Grosso" },
  { id: "TJMS", nome: "Tribunal de Justiça do Mato Grosso do Sul" },
  { id: "TJMG", nome: "Tribunal de Justiça de Minas Gerais" },
  { id: "TJPA", nome: "Tribunal de Justiça do Pará" },
  { id: "TJPB", nome: "Tribunal de Justiça da Paraíba" },
  { id: "TJPE", nome: "Tribunal de Justiça de Pernambuco" },
  { id: "TJPI", nome: "Tribunal de Justiça do Piauí" },
  { id: "TJPR", nome: "Tribunal de Justiça do Paraná" },
  { id: "TJRJ", nome: "Tribunal de Justiça do Rio de Janeiro" },
  { id: "TJRN", nome: "Tribunal de Justiça do Rio Grande do Norte" },
  { id: "TJRO", nome: "Tribunal de Justiça de Rondônia" },
  { id: "TJRR", nome: "Tribunal de Justiça de Roraima" },
  { id: "TJRS", nome: "Tribunal de Justiça do Rio Grande do Sul" },
  { id: "TJSC", nome: "Tribunal de Justiça de Santa Catarina" },
  { id: "TJSE", nome: "Tribunal de Justiça de Sergipe" },
  { id: "TJSP", nome: "Tribunal de Justiça de São Paulo" },
  { id: "TJTO", nome: "Tribunal de Justiça do Tocantins" },
  { id: "TRT1", nome: "Tribunal Regional do Trabalho da 1ª Região" },
  { id: "TRT2", nome: "Tribunal Regional do Trabalho da 2ª Região" },
  { id: "TRT3", nome: "Tribunal Regional do Trabalho da 3ª Região" },
  { id: "TRT4", nome: "Tribunal Regional do Trabalho da 4ª Região" },
  { id: "TRT5", nome: "Tribunal Regional do Trabalho da 5ª Região" },
  { id: "TRT6", nome: "Tribunal Regional do Trabalho da 6ª Região" },
  { id: "TRT7", nome: "Tribunal Regional do Trabalho da 7ª Região" },
  { id: "TRT8", nome: "Tribunal Regional do Trabalho da 8ª Região" },
  { id: "TRT9", nome: "Tribunal Regional do Trabalho da 9ª Região" },
  { id: "TRT10", nome: "Tribunal Regional do Trabalho da 10ª Região" },
  { id: "TRT11", nome: "Tribunal Regional do Trabalho da 11ª Região" },
  { id: "TRT12", nome: "Tribunal Regional do Trabalho da 12ª Região" },
  { id: "TRT13", nome: "Tribunal Regional do Trabalho da 13ª Região" },
  { id: "TRT14", nome: "Tribunal Regional do Trabalho da 14ª Região" },
  { id: "TRT15", nome: "Tribunal Regional do Trabalho da 15ª Região" },
  { id: "TRT16", nome: "Tribunal Regional do Trabalho da 16ª Região" },
  { id: "TRT17", nome: "Tribunal Regional do Trabalho da 17ª Região" },
  { id: "TRT18", nome: "Tribunal Regional do Trabalho da 18ª Região" },
  { id: "TRT19", nome: "Tribunal Regional do Trabalho da 19ª Região" },
  { id: "TRT20", nome: "Tribunal Regional do Trabalho da 20ª Região" },
  { id: "TRT21", nome: "Tribunal Regional do Trabalho da 21ª Região" },
  { id: "TRT22", nome: "Tribunal Regional do Trabalho da 22ª Região" },
  { id: "TRT23", nome: "Tribunal Regional do Trabalho da 23ª Região" },
  { id: "TRT24", nome: "Tribunal Regional do Trabalho da 24ª Região" },
].sort((a, b) => a.nome.localeCompare(b.nome));
